DELETE FROM public.game_answer WHERE true;
DELETE FROM public.game_session WHERE true;
DELETE FROM public.face WHERE true;
INSERT INTO public.face (file_path, name, gender, race) VALUES
('Male/face_0_East Asian_50-59', 'Frantisek Kriz', 'Male', 'East Asian'),
('Female/face_1_Indian_30-39', 'Alexandra Vackova', 'Female', 'Indian'),
('Female/face_2_Black_3-9', 'Daniela Markova', 'Female', 'Black'),
('Female/face_3_Indian_20-29', 'Marianna Toborek', 'Female', 'Indian'),
('Female/face_4_Indian_20-29', 'Nikol Krizova', 'Female', 'Indian'),
('Male/face_5_White_20-29', 'Marcel Malysiak', 'Male', 'White'),
('Male/face_6_Middle Eastern_40-49', 'Ignac Machacek', 'Male', 'Middle Eastern'),
('Female/face_7_Indian_30-39', 'Nora Benesova', 'Female', 'Indian'),
('Male/face_8_White_10-19', 'Arnost Kratochvil', 'Male', 'White'),
('Male/face_9_Middle Eastern_30-39', 'Ernest Horbacz', 'Male', 'Middle Eastern'),
('Male/face_10_East Asian_50-59', 'Marcin Bochnia', 'Male', 'East Asian'),
('Male/face_11_East Asian_20-29', 'Arnost Riha', 'Male', 'East Asian'),
('Male/face_12_Latino_Hispanic_20-29', 'Jozef Zeman', 'Male', 'Latino_Hispanic'),
('Male/face_13_Indian_10-19', 'Robin Nemecek', 'Male', 'Indian'),
('Female/face_14_Indian_60-69', 'Zdenka Ruzickova', 'Female', 'Indian'),
('Female/face_15_White_30-39', 'Adela Cermakova', 'Female', 'White'),
('Female/face_16_Southeast Asian_20-29', 'Marta Vankova', 'Female', 'Southeast Asian'),
('Male/face_17_Southeast Asian_40-49', 'Ludvik Jezek', 'Male', 'Southeast Asian'),
('Female/face_18_Black_0-2', 'Anastazie Ticha', 'Female', 'Black'),
('Male/face_19_Southeast Asian_50-59', 'Stefan Sedlacek', 'Male', 'Southeast Asian'),
('Female/face_20_Indian_20-29', 'Jitka Sedlakova', 'Female', 'Indian'),
('Female/face_21_Middle Eastern_30-39', 'Nela Matyjaszek', 'Female', 'Middle Eastern'),
('Female/face_22_Black_20-29', 'Magdalena Stankova', 'Female', 'Black'),
('Female/face_23_White_30-39', 'Albert Roter', 'Female', 'White'),
('Female/face_24_White_20-29', 'Borys Skonieczka', 'Female', 'White'),
('Female/face_25_Black_30-39', 'Stepanka Krejcova', 'Female', 'Black'),
('Female/face_26_White_50-59', 'Apolena Peskova', 'Female', 'White'),
('Female/face_27_White_10-19', 'Sara Wlazly', 'Female', 'White'),
('Male/face_28_Indian_20-29', 'Sandra Boduch', 'Male', 'Indian'),
('Female/face_29_Black_20-29', 'Anezka Horvathova', 'Female', 'Black'),
('Female/face_30_Black_40-49', 'Katerina Liskova', 'Female', 'Black'),
('Female/face_31_East Asian_10-19', 'Jakub Sierzant', 'Female', 'East Asian'),
('Male/face_32_White_50-59', 'Jerzy Apostel', 'Male', 'White'),
('Male/face_33_Middle Eastern_40-49', 'Jan Pokorny', 'Male', 'Middle Eastern'),
('Male/face_34_East Asian_20-29', 'Simon Kovar', 'Male', 'East Asian'),
('Female/face_35_Middle Eastern_60-69', 'Linda Vitkova', 'Female', 'Middle Eastern'),
('Female/face_36_Latino_Hispanic_20-29', 'Bohumila Fialova', 'Female', 'Latino_Hispanic'),
('Male/face_37_Latino_Hispanic_30-39', 'Matyas Jezek', 'Male', 'Latino_Hispanic'),
('Male/face_38_Middle Eastern_50-59', 'Julian Raba', 'Male', 'Middle Eastern'),
('Female/face_39_Latino_Hispanic_20-29', 'Jana Kasparova', 'Female', 'Latino_Hispanic'),
('Male/face_40_White_20-29', 'Veres Gyorgy', 'Male', 'White'),
('Female/face_41_Black_10-19', 'Marcela Vlckova', 'Female', 'Black'),
('Female/face_42_Southeast Asian_10-19', 'Gabriela Polakova', 'Female', 'Southeast Asian'),
('Male/face_43_Latino_Hispanic_40-49', 'Premysl Kral', 'Male', 'Latino_Hispanic'),
('Male/face_44_Indian_10-19', 'Patrik Sevcik', 'Male', 'Indian'),
('Female/face_45_Indian_10-19', 'Marcel Kielbus', 'Female', 'Indian'),
('Male/face_46_East Asian_60-69', 'Vladislav Mares', 'Male', 'East Asian'),
('Female/face_47_Middle Eastern_3-9', 'Olga Petrova', 'Female', 'Middle Eastern'),
('Female/face_48_Southeast Asian_10-19', 'Mariusz Gryka', 'Female', 'Southeast Asian'),
('Female/face_49_Black_50-59', 'Bohumila Zakova', 'Female', 'Black'),
('Female/face_50_East Asian_3-9', 'Marketa Stastna', 'Female', 'East Asian'),
('Male/face_51_Latino_Hispanic_60-69', 'Dominik Doroszuk', 'Male', 'Latino_Hispanic'),
('Male/face_52_Southeast Asian_50-59', 'Krystyna Wawszczyk', 'Male', 'Southeast Asian'),
('Female/face_53_East Asian_30-39', 'Julie Cermakova', 'Female', 'East Asian'),
('Male/face_54_Southeast Asian_30-39', 'Stanislaw Kutera', 'Male', 'Southeast Asian'),
('Male/face_55_White_30-39', 'Adrian Krysik', 'Male', 'White'),
('Male/face_56_Black_20-29', 'Dalibor Kovar', 'Male', 'Black'),
('Female/face_57_Latino_Hispanic_40-49', 'Borys Lenarcik', 'Female', 'Latino_Hispanic'),
('Female/face_58_Latino_Hispanic_10-19', 'Mateusz Kusio', 'Female', 'Latino_Hispanic'),
('Female/face_59_Latino_Hispanic_10-19', 'Patricie Horakova', 'Female', 'Latino_Hispanic'),
('Male/face_60_East Asian_3-9', 'Vlastimil Beran', 'Male', 'East Asian'),
('Male/face_61_Indian_10-19', 'Vilem Horak', 'Male', 'Indian'),
('Male/face_62_Indian_40-49', 'Alexander Maly', 'Male', 'Indian'),
('Male/face_63_Southeast Asian_20-29', 'Dusan Vesely', 'Male', 'Southeast Asian'),
('Male/face_64_East Asian_30-39', 'Krzysztof Scibior', 'Male', 'East Asian'),
('Male/face_65_Latino_Hispanic_30-39', 'Richard Masek', 'Male', 'Latino_Hispanic'),
('Female/face_66_Latino_Hispanic_10-19', 'Ada Dubel', 'Female', 'Latino_Hispanic'),
('Male/face_67_White_60-69', 'Aniela Andrzejuk', 'Male', 'White'),
('Male/face_68_Southeast Asian_50-59', 'Jan Machacek', 'Male', 'Southeast Asian'),
('Male/face_69_Indian_30-39', 'Bartek Golon', 'Male', 'Indian'),
('Female/face_70_Indian_60-69', 'Ivona Blazkova', 'Female', 'Indian'),
('Male/face_71_Latino_Hispanic_30-39', 'Peter Beran', 'Male', 'Latino_Hispanic'),
('Female/face_72_Latino_Hispanic_30-39', 'Radka Pavlikova', 'Female', 'Latino_Hispanic'),
('Female/face_73_Southeast Asian_20-29', 'Justyna Dybas', 'Female', 'Southeast Asian'),
('Male/face_74_Indian_30-39', 'Igor Miechowicz', 'Male', 'Indian'),
('Male/face_75_Southeast Asian_20-29', 'Kajetan Zolna', 'Male', 'Southeast Asian'),
('Female/face_76_Black_50-59', 'Eliza Pikor', 'Female', 'Black'),
('Female/face_77_Middle Eastern_20-29', 'Kornelia Golda', 'Female', 'Middle Eastern'),
('Male/face_78_Latino_Hispanic_40-49', 'Jakub Szalas', 'Male', 'Latino_Hispanic'),
('Male/face_79_White_30-39', 'Jozef Valenta', 'Male', 'White'),
('Female/face_80_Black_30-39', 'Julita Nowotny', 'Female', 'Black'),
('Male/face_81_Indian_30-39', 'Artur Nemec', 'Male', 'Indian'),
('Male/face_82_White_40-49', 'Oldrich Stanek', 'Male', 'White'),
('Female/face_83_Black_10-19', 'Drahomira Kubickova', 'Female', 'Black'),
('Female/face_84_White_20-29', 'Frantiska Slavikova', 'Female', 'White'),
('Female/face_85_Black_20-29', 'Vera Cerna', 'Female', 'Black'),
('Male/face_86_Black_20-29', 'Sebastian Zybura', 'Male', 'Black'),
('Female/face_87_Southeast Asian_20-29', 'Eva Liskova', 'Female', 'Southeast Asian'),
('Male/face_88_Indian_40-49', 'Antonin Kolar', 'Male', 'Indian'),
('Male/face_89_Indian_50-59', 'Adrian Pietrasiak', 'Male', 'Indian'),
('Male/face_90_Latino_Hispanic_30-39', 'Ignac Tichy', 'Male', 'Latino_Hispanic'),
('Female/face_91_East Asian_0-2', 'Aurelia Kudlacz', 'Female', 'East Asian'),
('Female/face_92_White_30-39', 'Julita Szafarz', 'Female', 'White'),
('Female/face_93_Latino_Hispanic_3-9', 'Leon Kastelik', 'Female', 'Latino_Hispanic'),
('Male/face_94_Black_20-29', 'Frantisek Jaros', 'Male', 'Black'),
('Female/face_95_White_30-39', 'Pavlina Dvorakova', 'Female', 'White'),
('Female/face_96_White_30-39', 'Renata Sevcikova', 'Female', 'White'),
('Female/face_97_East Asian_20-29', 'Julie Moravcova', 'Female', 'East Asian'),
('Male/face_98_White_30-39', 'Rafal Zelasko', 'Male', 'White'),
('Female/face_99_East Asian_20-29', 'Aneta Bartosova', 'Female', 'East Asian'),
('Male/face_100_Indian_30-39', 'Lubos Novak', 'Male', 'Indian'),
('Male/face_101_White_30-39', 'Michal Waniek', 'Male', 'White'),
('Male/face_102_Indian_40-49', 'Jozef Ochnio', 'Male', 'Indian'),
('Male/face_103_Indian_30-39', 'Rene Havlicek', 'Male', 'Indian'),
('Male/face_104_East Asian_50-59', 'Petr Zeman', 'Male', 'East Asian'),
('Male/face_105_Black_40-49', 'Jaromir Masek', 'Male', 'Black'),
('Female/face_106_White_30-39', 'Angelika Grzela', 'Female', 'White'),
('Female/face_107_Indian_more than 70', 'Bohumila Urbanova', 'Female', 'Indian'),
('Female/face_108_Middle Eastern_20-29', 'Jaroslava Dostalova', 'Female', 'Middle Eastern'),
('Male/face_109_White_30-39', 'Patrik Pavlicek', 'Male', 'White'),
('Female/face_110_Indian_40-49', 'Karolina Cechova', 'Female', 'Indian'),
('Female/face_111_Latino_Hispanic_40-49', 'Hegedus Dominikne', 'Female', 'Latino_Hispanic'),
('Male/face_112_Middle Eastern_30-39', 'Alexander Vitek', 'Male', 'Middle Eastern'),
('Female/face_113_White_30-39', 'Leonard Ciak', 'Female', 'White'),
('Male/face_114_Black_50-59', 'Michal Ziola', 'Male', 'Black'),
('Female/face_115_Latino_Hispanic_20-29', 'Leonard Dyda', 'Female', 'Latino_Hispanic'),
('Male/face_116_White_30-39', 'Adrian Sass', 'Male', 'White'),
('Male/face_117_White_30-39', 'Slavomir Tesar', 'Male', 'White'),
('Male/face_118_Indian_40-49', 'Marcin Mirocha', 'Male', 'Indian'),
('Male/face_119_Middle Eastern_60-69', 'Artur Guzdek', 'Male', 'Middle Eastern'),
('Female/face_120_White_20-29', 'Anna Mullerova', 'Female', 'White'),
('Female/face_121_East Asian_20-29', 'Szymon Ludwisiak', 'Female', 'East Asian'),
('Female/face_122_Black_30-39', 'Nadezda Janeckova', 'Female', 'Black'),
('Male/face_123_Indian_0-2', 'Emil Svec', 'Male', 'Indian'),
('Male/face_124_White_40-49', 'Emil Simek', 'Male', 'White'),
('Female/face_125_East Asian_30-39', 'Sebastian Kalwa', 'Female', 'East Asian'),
('Female/face_126_White_3-9', 'Vendula Cerna', 'Female', 'White'),
('Female/face_127_Indian_20-29', 'Andela Kolarova', 'Female', 'Indian'),
('Female/face_128_Black_10-19', 'Sara Hruba', 'Female', 'Black'),
('Male/face_129_White_50-59', 'Stepan Cerny', 'Male', 'White'),
('Female/face_130_Middle Eastern_30-39', 'Marek Talaj', 'Female', 'Middle Eastern'),
('Female/face_131_White_3-9', 'Nataniel Kandora', 'Female', 'White'),
('Male/face_132_Latino_Hispanic_3-9', 'Kocsis Janos', 'Male', 'Latino_Hispanic'),
('Male/face_133_White_30-39', 'Slavomir Bednar', 'Male', 'White'),
('Female/face_134_White_40-49', 'Alzbeta Sevcikova', 'Female', 'White'),
('Female/face_135_Indian_50-59', 'Pavlina Fialova', 'Female', 'Indian'),
('Male/face_136_Latino_Hispanic_40-49', 'Szucs Erno', 'Male', 'Latino_Hispanic'),
('Male/face_137_Black_50-59', 'Roman Bures', 'Male', 'Black'),
('Female/face_138_East Asian_30-39', 'Dorota Kadlecova', 'Female', 'East Asian'),
('Female/face_139_East Asian_20-29', 'Michaela Navratilova', 'Female', 'East Asian'),
('Male/face_140_Latino_Hispanic_10-19', 'Rudolf Blaha', 'Male', 'Latino_Hispanic'),
('Male/face_141_East Asian_30-39', 'Robert Kondej', 'Male', 'East Asian'),
('Male/face_142_Indian_30-39', 'Denis Fiser', 'Male', 'Indian'),
('Male/face_143_East Asian_more than 70', 'Vasyl Valenta', 'Male', 'East Asian'),
('Male/face_144_White_30-39', 'Cyprian Kocwin', 'Male', 'White'),
('Male/face_145_Southeast Asian_40-49', 'Fabian Apostel', 'Male', 'Southeast Asian'),
('Male/face_146_Southeast Asian_40-49', 'Jindrich Sykora', 'Male', 'Southeast Asian'),
('Male/face_147_Southeast Asian_50-59', 'Samuel Liska', 'Male', 'Southeast Asian'),
('Male/face_148_Indian_50-59', 'Tadeas Kolar', 'Male', 'Indian'),
('Male/face_149_Latino_Hispanic_20-29', 'Kovacs Janos', 'Male', 'Latino_Hispanic'),
('Female/face_150_Black_20-29', 'Svetlana Berankova', 'Female', 'Black'),
('Male/face_151_Middle Eastern_20-29', 'Roksana Lasak', 'Male', 'Middle Eastern'),
('Female/face_152_Southeast Asian_20-29', 'Sarkozi Margit', 'Female', 'Southeast Asian'),
('Male/face_153_White_30-39', 'Budai Mihaly', 'Male', 'White'),
('Male/face_154_Southeast Asian_20-29', 'Simon Zak', 'Male', 'Southeast Asian'),
('Male/face_155_Latino_Hispanic_20-29', 'Jan Pokorny', 'Male', 'Latino_Hispanic'),
('Male/face_156_White_20-29', 'Mieszko Karkut', 'Male', 'White'),
('Male/face_157_Black_3-9', 'Marcel Bakun', 'Male', 'Black'),
('Female/face_158_Indian_30-39', 'Mikolaj Rubaj', 'Female', 'Indian'),
('Female/face_159_Black_40-49', 'Michal Pabisiak', 'Female', 'Black'),
('Female/face_160_Latino_Hispanic_10-19', 'Lydie Buresova', 'Female', 'Latino_Hispanic'),
('Female/face_161_White_30-39', 'Elena Krejcova', 'Female', 'White'),
('Male/face_162_Southeast Asian_10-19', 'Mieszko Kubek', 'Male', 'Southeast Asian'),
('Female/face_163_East Asian_20-29', 'Aleks Gleba', 'Female', 'East Asian'),
('Female/face_164_Southeast Asian_50-59', 'Hedvika Slavikova', 'Female', 'Southeast Asian'),
('Male/face_165_East Asian_3-9', 'Dominik Bicz', 'Male', 'East Asian'),
('Female/face_166_Latino_Hispanic_30-39', 'Milena Sedlakova', 'Female', 'Latino_Hispanic'),
('Female/face_167_Southeast Asian_20-29', 'Oskar Stanislawek', 'Female', 'Southeast Asian'),
('Male/face_168_East Asian_20-29', 'Dorota Soroko', 'Male', 'East Asian'),
('Female/face_169_Southeast Asian_20-29', 'Inga Niksa', 'Female', 'Southeast Asian'),
('Female/face_170_White_30-39', 'Lydie Hajkova', 'Female', 'White'),
('Male/face_171_Southeast Asian_10-19', 'Takacs Lajos', 'Male', 'Southeast Asian'),
('Female/face_172_Latino_Hispanic_20-29', 'Adrianna Bojdo', 'Female', 'Latino_Hispanic'),
('Male/face_173_Indian_60-69', 'Albert Kolman', 'Male', 'Indian'),
('Female/face_174_Indian_20-29', 'Maks Welc', 'Female', 'Indian'),
('Female/face_175_White_60-69', 'Nina Novakova', 'Female', 'White'),
('Female/face_176_White_30-39', 'Adrianna Dziurdzia', 'Female', 'White'),
('Male/face_177_White_30-39', 'Samuel Polak', 'Male', 'White'),
('Female/face_178_Black_10-19', 'Michal Sterna', 'Female', 'Black'),
('Male/face_179_Middle Eastern_30-39', 'Bianka Przewozny', 'Male', 'Middle Eastern'),
('Female/face_180_Latino_Hispanic_20-29', 'Dawid Sosniak', 'Female', 'Latino_Hispanic'),
('Male/face_181_Black_40-49', 'Szabo Peter', 'Male', 'Black'),
('Female/face_182_Black_20-29', 'Aneta Vitkova', 'Female', 'Black'),
('Male/face_183_White_20-29', 'Racz Csongor', 'Male', 'White'),
('Male/face_184_Black_3-9', 'David Slavik', 'Male', 'Black'),
('Female/face_185_Southeast Asian_50-59', 'Lakatos Jozsefne', 'Female', 'Southeast Asian'),
('Female/face_186_Middle Eastern_30-39', 'Hana Kadlecova', 'Female', 'Middle Eastern'),
('Female/face_187_Indian_3-9', 'Sabina Ticha', 'Female', 'Indian'),
('Female/face_188_East Asian_3-9', 'Dana Kratochvilova', 'Female', 'East Asian'),
('Male/face_189_East Asian_10-19', 'Natan Stanaszek', 'Male', 'East Asian'),
('Female/face_190_East Asian_20-29', 'Michaela Bilkova', 'Female', 'East Asian'),
('Female/face_191_White_10-19', 'Radka Stankova', 'Female', 'White'),
('Male/face_192_White_60-69', 'Jan Musil', 'Male', 'White'),
('Male/face_193_East Asian_20-29', 'Radoslav Horak', 'Male', 'East Asian'),
('Male/face_194_Black_40-49', 'Jan Hruby', 'Male', 'Black'),
('Female/face_195_Middle Eastern_20-29', 'Sandor Milanne', 'Female', 'Middle Eastern'),
('Female/face_196_White_40-49', 'Jedrzej Andrejczuk', 'Female', 'White'),
('Female/face_197_Indian_10-19', 'Fabian Krzysko', 'Female', 'Indian'),
('Female/face_198_Latino_Hispanic_20-29', 'Marika Madura', 'Female', 'Latino_Hispanic'),
('Male/face_199_Indian_10-19', 'Dorota Tomaszuk', 'Male', 'Indian'),
('Female/face_200_Latino_Hispanic_40-49', 'Gustaw Zander', 'Female', 'Latino_Hispanic'),
('Male/face_201_Black_40-49', 'Jan Moravec', 'Male', 'Black'),
('Male/face_202_White_20-29', 'Robin Havlicek', 'Male', 'White'),
('Female/face_203_East Asian_20-29', 'Daniela Kucerova', 'Female', 'East Asian'),
('Female/face_204_Southeast Asian_3-9', 'Anna Sevcikova', 'Female', 'Southeast Asian'),
('Female/face_205_White_50-59', 'Leonard Jasica', 'Female', 'White'),
('Female/face_206_Middle Eastern_20-29', 'Adela Berankova', 'Female', 'Middle Eastern'),
('Female/face_207_Indian_30-39', 'Monika Petrova', 'Female', 'Indian'),
('Female/face_208_Black_30-39', 'Olivie Slavikova', 'Female', 'Black'),
('Male/face_209_Black_3-9', 'Arkadiusz Pyrz', 'Male', 'Black'),
('Male/face_210_Southeast Asian_20-29', 'Rozalia Piesik', 'Male', 'Southeast Asian'),
('Male/face_211_East Asian_3-9', 'Alan Lewicz', 'Male', 'East Asian'),
('Male/face_212_White_50-59', 'Olga Koska', 'Male', 'White'),
('Male/face_213_White_50-59', 'Marcin Jachimczak', 'Male', 'White'),
('Female/face_214_Black_30-39', 'Artur Misko', 'Female', 'Black'),
('Male/face_215_Black_50-59', 'Vaclav Machacek', 'Male', 'Black'),
('Male/face_216_Indian_40-49', 'Emil Nagel', 'Male', 'Indian'),
('Female/face_217_Middle Eastern_30-39', 'Karina Parkitna', 'Female', 'Middle Eastern'),
('Female/face_218_Southeast Asian_30-39', 'Arkadiusz Symonowicz', 'Female', 'Southeast Asian'),
('Male/face_219_Latino_Hispanic_3-9', 'Klara Czescik', 'Male', 'Latino_Hispanic'),
('Female/face_220_White_3-9', 'Viktorie Janeckova', 'Female', 'White'),
('Male/face_221_Middle Eastern_30-39', 'Ctirad Pavlicek', 'Male', 'Middle Eastern'),
('Male/face_222_Latino_Hispanic_50-59', 'Lubomir Muller', 'Male', 'Latino_Hispanic'),
('Female/face_223_Latino_Hispanic_40-49', 'Krystian Swiergiel', 'Female', 'Latino_Hispanic'),
('Male/face_224_Middle Eastern_40-49', 'Josef Toman', 'Male', 'Middle Eastern'),
('Female/face_225_Southeast Asian_20-29', 'Julita Sorbian', 'Female', 'Southeast Asian'),
('Male/face_226_Middle Eastern_30-39', 'Malwina Piksa', 'Male', 'Middle Eastern'),
('Female/face_227_Indian_20-29', 'Elena Vankova', 'Female', 'Indian'),
('Male/face_228_Latino_Hispanic_30-39', 'Kornel Joszko', 'Male', 'Latino_Hispanic'),
('Male/face_229_White_50-59', 'Igor Horvath', 'Male', 'White'),
('Male/face_230_Southeast Asian_30-39', 'Martin Blazek', 'Male', 'Southeast Asian'),
('Male/face_231_Middle Eastern_50-59', 'Jindrich Vitek', 'Male', 'Middle Eastern'),
('Male/face_232_Middle Eastern_20-29', 'Fabian Adrian', 'Male', 'Middle Eastern'),
('Male/face_233_White_40-49', 'Krystof Tichy', 'Male', 'White'),
('Female/face_234_East Asian_20-29', 'Lada Sykorova', 'Female', 'East Asian'),
('Female/face_235_Southeast Asian_20-29', 'Frantiska Machova', 'Female', 'Southeast Asian'),
('Male/face_236_Indian_30-39', 'Bohumir Kubicek', 'Male', 'Indian'),
('Male/face_237_Southeast Asian_30-39', 'Radoslav Simek', 'Male', 'Southeast Asian'),
('Female/face_238_White_30-39', 'Aleks Macha', 'Female', 'White'),
('Female/face_239_Indian_20-29', 'Mariusz Senator', 'Female', 'Indian'),
('Male/face_240_White_30-39', 'Fryderyk Kalwak', 'Male', 'White'),
('Female/face_241_Indian_20-29', 'Olaf Franc', 'Female', 'Indian'),
('Female/face_242_Southeast Asian_40-49', 'Eliza Kopa', 'Female', 'Southeast Asian'),
('Female/face_243_Black_40-49', 'Orban Laszlone', 'Female', 'Black'),
('Female/face_244_Southeast Asian_20-29', 'Natalie Kratochvilova', 'Female', 'Southeast Asian'),
('Male/face_245_White_20-29', 'Kamil Pokorny', 'Male', 'White'),
('Female/face_246_Indian_20-29', 'Artur Felisiak', 'Female', 'Indian'),
('Male/face_247_Black_3-9', 'Horvath Richard', 'Male', 'Black'),
('Male/face_248_Indian_10-19', 'Varga Mihaly', 'Male', 'Indian'),
('Female/face_249_East Asian_30-39', 'Leona Stastna', 'Female', 'East Asian'),
('Male/face_250_Black_3-9', 'Marcel Vavra', 'Male', 'Black'),
('Female/face_251_East Asian_20-29', 'Krzysztof Chmara', 'Female', 'East Asian'),
('Male/face_252_Southeast Asian_3-9', 'Rudolf Svec', 'Male', 'Southeast Asian'),
('Male/face_253_Latino_Hispanic_3-9', 'Matyas Hruska', 'Male', 'Latino_Hispanic'),
('Female/face_254_Southeast Asian_more than 70', 'Linda Peskova', 'Female', 'Southeast Asian'),
('Male/face_255_East Asian_3-9', 'Elzbieta Wlodyka', 'Male', 'East Asian'),
('Female/face_256_Latino_Hispanic_10-19', 'Apolena Konecna', 'Female', 'Latino_Hispanic'),
('Male/face_257_Southeast Asian_3-9', 'Mieszko Kajstura', 'Male', 'Southeast Asian'),
('Female/face_258_Latino_Hispanic_10-19', 'Leona Prochazkova', 'Female', 'Latino_Hispanic'),
('Male/face_259_Black_20-29', 'Sandra Danilczuk', 'Male', 'Black'),
('Male/face_260_Latino_Hispanic_30-39', 'Malwina Orpel', 'Male', 'Latino_Hispanic'),
('Male/face_261_Black_3-9', 'Josef Sevcik', 'Male', 'Black'),
('Female/face_262_Black_40-49', 'Kveta Horackova', 'Female', 'Black'),
('Male/face_263_Southeast Asian_10-19', 'Simon Novotny', 'Male', 'Southeast Asian'),
('Female/face_264_White_30-39', 'Karol Jedrys', 'Female', 'White'),
('Male/face_265_Latino_Hispanic_10-19', 'Jaromir Stejskal', 'Male', 'Latino_Hispanic'),
('Male/face_266_Black_40-49', 'Artur Matejka', 'Male', 'Black'),
('Male/face_267_Latino_Hispanic_20-29', 'Nikodem Gaudyn', 'Male', 'Latino_Hispanic'),
('Female/face_268_Southeast Asian_20-29', 'Farkas Mihalyne', 'Female', 'Southeast Asian'),
('Female/face_269_Latino_Hispanic_20-29', 'Filip Kuczak', 'Female', 'Latino_Hispanic'),
('Female/face_270_Southeast Asian_20-29', 'Miluse Hajkova', 'Female', 'Southeast Asian'),
('Male/face_271_White_40-49', 'Dominik Tichy', 'Male', 'White'),
('Male/face_272_Indian_30-39', 'Radovan Havlicek', 'Male', 'Indian'),
('Male/face_273_Black_30-39', 'Liwia Matyjasek', 'Male', 'Black'),
('Male/face_274_Black_10-19', 'Leos Hruska', 'Male', 'Black'),
('Male/face_275_Black_3-9', 'Ivan Havlicek', 'Male', 'Black'),
('Male/face_276_Indian_3-9', 'Ctirad Cermak', 'Male', 'Indian'),
('Female/face_277_White_3-9', 'Jana Horakova', 'Female', 'White'),
('Female/face_278_Latino_Hispanic_20-29', 'Lukasz Pres', 'Female', 'Latino_Hispanic'),
('Male/face_279_White_30-39', 'Daniel Vlcek', 'Male', 'White'),
('Male/face_280_Indian_30-39', 'Zdenek Matejka', 'Male', 'Indian'),
('Female/face_281_Black_40-49', 'Angelika Bona', 'Female', 'Black'),
('Male/face_282_East Asian_40-49', 'Ignacy Dusik', 'Male', 'East Asian'),
('Female/face_283_Latino_Hispanic_10-19', 'Jirina Moravcova', 'Female', 'Latino_Hispanic'),
('Male/face_284_White_30-39', 'Otakar Jezek', 'Male', 'White'),
('Male/face_285_Southeast Asian_20-29', 'Jindrich Barta', 'Male', 'Southeast Asian'),
('Male/face_286_Black_3-9', 'Apolonia Dziarmaga', 'Male', 'Black'),
('Female/face_287_East Asian_20-29', 'Tomasz Zegadlo', 'Female', 'East Asian'),
('Female/face_288_Black_30-39', 'Andela Mullerova', 'Female', 'Black'),
('Male/face_289_East Asian_10-19', 'Jan Matejka', 'Male', 'East Asian'),
('Male/face_290_Latino_Hispanic_50-59', 'Vasyl Stastny', 'Male', 'Latino_Hispanic'),
('Female/face_291_White_20-29', 'Filip Perczak', 'Female', 'White'),
('Male/face_292_Black_10-19', 'Jeremi Zeman', 'Male', 'Black'),
('Female/face_293_Southeast Asian_3-9', 'Wiktor Banek', 'Female', 'Southeast Asian'),
('Male/face_294_Latino_Hispanic_30-39', 'Anastazja Falba', 'Male', 'Latino_Hispanic'),
('Female/face_295_Latino_Hispanic_20-29', 'Marta Valentova', 'Female', 'Latino_Hispanic'),
('Female/face_296_Southeast Asian_30-39', 'Judita Dostalova', 'Female', 'Southeast Asian'),
('Male/face_297_White_20-29', 'Arnost Matousek', 'Male', 'White'),
('Male/face_298_White_40-49', 'Aleksander Maslankiewicz', 'Male', 'White'),
('Female/face_299_Black_3-9', 'Nataniel Lukasz', 'Female', 'Black'),
('Male/face_300_Middle Eastern_30-39', 'Radek Kadlec', 'Male', 'Middle Eastern'),
('Female/face_301_Black_3-9', 'Kamil Swistek', 'Female', 'Black'),
('Female/face_302_White_20-29', 'Kovacs Judit', 'Female', 'White'),
('Female/face_303_Middle Eastern_3-9', 'Lidia Malara', 'Female', 'Middle Eastern'),
('Female/face_304_Indian_30-39', 'Julianna Tabak', 'Female', 'Indian'),
('Male/face_305_Latino_Hispanic_50-59', 'Dorota Fierek', 'Male', 'Latino_Hispanic'),
('Female/face_306_East Asian_30-39', 'Nagy Lilla', 'Female', 'East Asian'),
('Male/face_307_Middle Eastern_20-29', 'Marcel Martynowicz', 'Male', 'Middle Eastern'),
('Female/face_308_White_40-49', 'Otylie Maresova', 'Female', 'White'),
('Male/face_309_Middle Eastern_30-39', 'Marcel Pierz', 'Male', 'Middle Eastern'),
('Female/face_310_East Asian_20-29', 'Pavlina Kasparova', 'Female', 'East Asian'),
('Female/face_311_Middle Eastern_20-29', 'Stefan Jandula', 'Female', 'Middle Eastern'),
('Male/face_312_Black_20-29', 'Ada Nozka', 'Male', 'Black'),
('Male/face_313_Black_40-49', 'Inga Michel', 'Male', 'Black'),
('Male/face_314_Indian_30-39', 'Ales Slavik', 'Male', 'Indian'),
('Male/face_315_Latino_Hispanic_30-39', 'Dominik Witkowicz', 'Male', 'Latino_Hispanic'),
('Female/face_316_Southeast Asian_30-39', 'Patricie Hajkova', 'Female', 'Southeast Asian'),
('Male/face_317_White_40-49', 'Nagy Tamas', 'Male', 'White'),
('Female/face_318_Indian_10-19', 'Julita Jakiel', 'Female', 'Indian'),
('Female/face_319_East Asian_20-29', 'Dariusz Gradek', 'Female', 'East Asian'),
('Female/face_320_Indian_3-9', 'Sona Benesova', 'Female', 'Indian'),
('Female/face_321_White_20-29', 'Dorota Horvathova', 'Female', 'White'),
('Male/face_322_White_60-69', 'Hubert Marek', 'Male', 'White'),
('Female/face_323_Latino_Hispanic_40-49', 'Jolana Prochazkova', 'Female', 'Latino_Hispanic'),
('Female/face_324_East Asian_30-39', 'Bozena Sykorova', 'Female', 'East Asian'),
('Male/face_325_East Asian_40-49', 'Ewa Pezda', 'Male', 'East Asian'),
('Male/face_326_Black_3-9', 'Antonin Novotny', 'Male', 'Black'),
('Male/face_327_Indian_50-59', 'Varga Ferenc', 'Male', 'Indian'),
('Male/face_328_East Asian_30-39', 'Ctibor Hruby', 'Male', 'East Asian'),
('Female/face_329_East Asian_20-29', 'Barbora Dvorakova', 'Female', 'East Asian'),
('Female/face_330_White_20-29', 'Vera Urbanova', 'Female', 'White'),
('Female/face_331_Latino_Hispanic_40-49', 'Hana Valentova', 'Female', 'Latino_Hispanic'),
('Male/face_332_White_20-29', 'Kovacs Antal', 'Male', 'White'),
('Male/face_333_White_40-49', 'Mikolaj Orawiec', 'Male', 'White'),
('Female/face_334_East Asian_20-29', 'Maksymilian Sapeta', 'Female', 'East Asian'),
('Female/face_335_Latino_Hispanic_30-39', 'Jacek Miodek', 'Female', 'Latino_Hispanic'),
('Male/face_336_White_50-59', 'Slavomir Kucera', 'Male', 'White'),
('Male/face_337_Indian_3-9', 'Konstanty Jaje', 'Male', 'Indian'),
('Female/face_338_White_20-29', 'Ilona Ticha', 'Female', 'White'),
('Male/face_339_White_3-9', 'Marcel Bastek', 'Male', 'White'),
('Female/face_340_Southeast Asian_20-29', 'Ema Havlickova', 'Female', 'Southeast Asian'),
('Female/face_341_Indian_40-49', 'Alzbeta Markova', 'Female', 'Indian'),
('Male/face_342_Indian_20-29', 'Ludek Horacek', 'Male', 'Indian'),
('Female/face_343_Middle Eastern_3-9', 'Olga Bakalarczyk', 'Female', 'Middle Eastern'),
('Male/face_344_Latino_Hispanic_20-29', 'Adam Slavik', 'Male', 'Latino_Hispanic'),
('Female/face_345_White_30-39', 'Kacper Wujec', 'Female', 'White'),
('Male/face_346_Southeast Asian_20-29', 'Bianka Kolber', 'Male', 'Southeast Asian'),
('Female/face_347_White_0-2', 'Kvetoslava Polakova', 'Female', 'White'),
('Male/face_348_Indian_40-49', 'Jiri Navratil', 'Male', 'Indian'),
('Male/face_349_Middle Eastern_20-29', 'Teodor Novotny', 'Male', 'Middle Eastern'),
('Male/face_350_White_30-39', 'Jan Vitek', 'Male', 'White'),
('Male/face_351_Black_50-59', 'Arnost Hruska', 'Male', 'Black'),
('Male/face_352_East Asian_50-59', 'Bohumil Blazek', 'Male', 'East Asian'),
('Male/face_353_Latino_Hispanic_50-59', 'Przemyslaw Ksiezyk', 'Male', 'Latino_Hispanic'),
('Female/face_354_East Asian_30-39', 'Balogh Terezia', 'Female', 'East Asian'),
('Female/face_355_Southeast Asian_0-2', 'Nela Jarosova', 'Female', 'Southeast Asian'),
('Male/face_356_East Asian_30-39', 'Jan Konecny', 'Male', 'East Asian'),
('Female/face_357_East Asian_20-29', 'Tomasz Pasiak', 'Female', 'East Asian'),
('Female/face_358_White_20-29', 'Meszaros Andrea', 'Female', 'White'),
('Male/face_359_Southeast Asian_10-19', 'Matej Slavik', 'Male', 'Southeast Asian'),
('Female/face_360_Latino_Hispanic_30-39', 'Jirina Soukupova', 'Female', 'Latino_Hispanic'),
('Male/face_361_Middle Eastern_3-9', 'Hubert Sedlak', 'Male', 'Middle Eastern'),
('Male/face_362_Southeast Asian_30-39', 'Milan Slavik', 'Male', 'Southeast Asian'),
('Female/face_363_Indian_3-9', 'Elzbieta Zimon', 'Female', 'Indian'),
('Male/face_364_Indian_10-19', 'Norbert Machacek', 'Male', 'Indian'),
('Female/face_365_Latino_Hispanic_20-29', 'Mariusz Kosiec', 'Female', 'Latino_Hispanic'),
('Male/face_366_Middle Eastern_30-39', 'Maksymilian Balawender', 'Male', 'Middle Eastern'),
('Female/face_367_Indian_20-29', 'Blazena Slavikova', 'Female', 'Indian'),
('Female/face_368_East Asian_40-49', 'Vendula Liskova', 'Female', 'East Asian'),
('Male/face_369_Black_30-39', 'Leonard Komisarek', 'Male', 'Black'),
('Male/face_370_Latino_Hispanic_50-59', 'Martin Hajek', 'Male', 'Latino_Hispanic'),
('Male/face_371_Middle Eastern_30-39', 'Ivo Kadlec', 'Male', 'Middle Eastern'),
('Male/face_372_East Asian_30-39', 'Filip Jedral', 'Male', 'East Asian'),
('Female/face_373_Southeast Asian_20-29', 'Gabriel Doroz', 'Female', 'Southeast Asian'),
('Male/face_374_Indian_30-39', 'Marcin Niklewicz', 'Male', 'Indian'),
('Male/face_375_Black_20-29', 'Lumir Kriz', 'Male', 'Black'),
('Female/face_376_Latino_Hispanic_50-59', 'Jakub Kostek', 'Female', 'Latino_Hispanic'),
('Male/face_377_Southeast Asian_30-39', 'Filip Tutka', 'Male', 'Southeast Asian'),
('Male/face_378_Latino_Hispanic_50-59', 'Rozalia Zontek', 'Male', 'Latino_Hispanic'),
('Female/face_379_White_40-49', 'Iveta Zemanova', 'Female', 'White'),
('Female/face_380_Middle Eastern_30-39', 'Dominika Liskova', 'Female', 'Middle Eastern'),
('Female/face_381_East Asian_30-39', 'Ester Peskova', 'Female', 'East Asian'),
('Female/face_382_East Asian_30-39', 'Kovacs Istvanne', 'Female', 'East Asian'),
('Female/face_383_Black_20-29', 'Juhasz Beatrix', 'Female', 'Black'),
('Male/face_384_Middle Eastern_40-49', 'Robert Havlicek', 'Male', 'Middle Eastern'),
('Male/face_385_East Asian_20-29', 'Tomasz Pawlaczek', 'Male', 'East Asian'),
('Male/face_386_Middle Eastern_30-39', 'Hubert Beran', 'Male', 'Middle Eastern'),
('Female/face_387_Black_10-19', 'Veronika Kralova', 'Female', 'Black'),
('Female/face_388_East Asian_30-39', 'Julita Tomal', 'Female', 'East Asian'),
('Male/face_389_East Asian_20-29', 'Vlastimil Cerny', 'Male', 'East Asian'),
('Female/face_390_East Asian_3-9', 'Dominik Minkiewicz', 'Female', 'East Asian'),
('Male/face_391_Black_10-19', 'Miloslav Bednar', 'Male', 'Black'),
('Female/face_392_Indian_10-19', 'Sarka Pokorna', 'Female', 'Indian'),
('Male/face_393_Latino_Hispanic_3-9', 'Mojmir Masek', 'Male', 'Latino_Hispanic'),
('Male/face_394_Middle Eastern_50-59', 'Marcel Cichos', 'Male', 'Middle Eastern'),
('Female/face_395_White_20-29', 'Bohumila Blahova', 'Female', 'White'),
('Male/face_396_Middle Eastern_0-2', 'Kazimierz Chmielak', 'Male', 'Middle Eastern'),
('Male/face_397_East Asian_50-59', 'Stefan Policht', 'Male', 'East Asian'),
('Female/face_398_Middle Eastern_10-19', 'Sara Fiserova', 'Female', 'Middle Eastern'),
('Male/face_399_Black_20-29', 'Tola Lokietek', 'Male', 'Black'),
('Male/face_400_Indian_40-49', 'Apolonia Szlufik', 'Male', 'Indian'),
('Male/face_401_Latino_Hispanic_30-39', 'Ivo Sevcik', 'Male', 'Latino_Hispanic'),
('Male/face_402_Indian_30-39', 'Ernest Zal', 'Male', 'Indian'),
('Male/face_403_Indian_30-39', 'Petr Prokop', 'Male', 'Indian'),
('Female/face_404_Latino_Hispanic_20-29', 'Melania Geisler', 'Female', 'Latino_Hispanic'),
('Male/face_405_White_60-69', 'Arnost Bartos', 'Male', 'White'),
('Female/face_406_Latino_Hispanic_20-29', 'Sabina Soukupova', 'Female', 'Latino_Hispanic'),
('Male/face_407_Latino_Hispanic_10-19', 'Matej Zak', 'Male', 'Latino_Hispanic'),
('Female/face_408_White_30-39', 'Sonia Miszta', 'Female', 'White'),
('Male/face_409_Latino_Hispanic_20-29', 'Arkadiusz Kuziora', 'Male', 'Latino_Hispanic'),
('Female/face_410_Latino_Hispanic_20-29', 'Ksawery Suszka', 'Female', 'Latino_Hispanic'),
('Male/face_411_East Asian_3-9', 'Robert Kriz', 'Male', 'East Asian'),
('Female/face_412_White_30-39', 'Alex Kiljan', 'Female', 'White'),
('Male/face_413_Black_3-9', 'Krzysztof Dryka', 'Male', 'Black'),
('Male/face_414_Indian_30-39', 'Kajetan Filiks', 'Male', 'Indian'),
('Female/face_415_Southeast Asian_3-9', 'Iveta Sedlakova', 'Female', 'Southeast Asian'),
('Male/face_416_Middle Eastern_3-9', 'Adam Oska', 'Male', 'Middle Eastern'),
('Male/face_417_Middle Eastern_more than 70', 'Mieszko Pielka', 'Male', 'Middle Eastern'),
('Male/face_418_White_30-39', 'Maurycy Furmankiewicz', 'Male', 'White'),
('Female/face_419_White_40-49', 'Slavena Horvathova', 'Female', 'White'),
('Male/face_420_Southeast Asian_10-19', 'Jan Kadlec', 'Male', 'Southeast Asian'),
('Male/face_421_East Asian_10-19', 'Alexandr Zeman', 'Male', 'East Asian'),
('Male/face_422_Latino_Hispanic_20-29', 'Vojtech Mach', 'Male', 'Latino_Hispanic'),
('Female/face_423_Black_3-9', 'Maciej Mizgala', 'Female', 'Black'),
('Male/face_424_Indian_20-29', 'Maksymilian Frankow', 'Male', 'Indian'),
('Female/face_425_Southeast Asian_20-29', 'Ilona Dolezalova', 'Female', 'Southeast Asian'),
('Female/face_426_White_30-39', 'Evelina Fialova', 'Female', 'White'),
('Male/face_427_Southeast Asian_20-29', 'Robin Kraus', 'Male', 'Southeast Asian'),
('Female/face_428_White_30-39', 'Alzbeta Havlickova', 'Female', 'White'),
('Female/face_429_Latino_Hispanic_20-29', 'Zdislava Rihova', 'Female', 'Latino_Hispanic'),
('Female/face_430_Latino_Hispanic_20-29', 'Farkas Imrene', 'Female', 'Latino_Hispanic'),
('Male/face_431_Indian_60-69', 'Leon Ziajka', 'Male', 'Indian'),
('Female/face_432_Black_10-19', 'Vladimira Horvathova', 'Female', 'Black'),
('Female/face_433_White_30-39', 'Ivana Navratilova', 'Female', 'White'),
('Female/face_434_Latino_Hispanic_30-39', 'Nina Hruskova', 'Female', 'Latino_Hispanic'),
('Male/face_435_Middle Eastern_20-29', 'Damian Musiolik', 'Male', 'Middle Eastern'),
('Male/face_436_Indian_0-2', 'Maksymilian Waleczek', 'Male', 'Indian'),
('Female/face_437_Middle Eastern_20-29', 'Arkadiusz Saternus', 'Female', 'Middle Eastern'),
('Female/face_438_Indian_20-29', 'Linda Cerna', 'Female', 'Indian'),
('Female/face_439_Black_40-49', 'Leona Ruzickova', 'Female', 'Black'),
('Female/face_440_White_20-29', 'Zdenka Matouskova', 'Female', 'White'),
('Female/face_441_Latino_Hispanic_20-29', 'Agata Blazkova', 'Female', 'Latino_Hispanic'),
('Male/face_442_White_40-49', 'Kamila Winek', 'Male', 'White'),
('Male/face_443_White_20-29', 'Michal Hak', 'Male', 'White'),
('Female/face_444_Indian_20-29', 'Patryk Wujec', 'Female', 'Indian'),
('Male/face_445_East Asian_20-29', 'Dominik Vanek', 'Male', 'East Asian'),
('Female/face_446_Black_40-49', 'Drahoslava Valentova', 'Female', 'Black'),
('Male/face_447_Latino_Hispanic_more than 70', 'Ewa Kunc', 'Male', 'Latino_Hispanic'),
('Male/face_448_East Asian_30-39', 'Damian Ryfa', 'Male', 'East Asian'),
('Male/face_449_Southeast Asian_10-19', 'Krystian Kraszkiewicz', 'Male', 'Southeast Asian'),
('Female/face_450_East Asian_3-9', 'Szabo Mihalyne', 'Female', 'East Asian'),
('Female/face_451_East Asian_20-29', 'Hedvika Slavikova', 'Female', 'East Asian'),
('Female/face_452_Southeast Asian_40-49', 'Sebastian Hojda', 'Female', 'Southeast Asian'),
('Female/face_453_White_20-29', 'Wiktor Bzdziuch', 'Female', 'White'),
('Male/face_454_White_20-29', 'Aleksander Maciuszek', 'Male', 'White'),
('Male/face_455_White_60-69', 'Oliwier Pusz', 'Male', 'White'),
('Male/face_456_Black_20-29', 'Horymir Simek', 'Male', 'Black'),
('Female/face_457_Latino_Hispanic_0-2', 'Liwia Ziemkiewicz', 'Female', 'Latino_Hispanic'),
('Female/face_458_White_10-19', 'Mieszko Martin', 'Female', 'White'),
('Female/face_459_East Asian_3-9', 'Renata Jarosova', 'Female', 'East Asian'),
('Male/face_460_East Asian_20-29', 'Leon Sommerfeld', 'Male', 'East Asian'),
('Female/face_461_East Asian_20-29', 'Veronika Maresova', 'Female', 'East Asian'),
('Male/face_462_Middle Eastern_50-59', 'Gal Adam', 'Male', 'Middle Eastern'),
('Male/face_463_Black_3-9', 'Alan Trzcionka', 'Male', 'Black'),
('Male/face_464_East Asian_30-39', 'Rudolf Holub', 'Male', 'East Asian'),
('Female/face_465_Southeast Asian_30-39', 'Ivana Mala', 'Female', 'Southeast Asian'),
('Female/face_466_Indian_20-29', 'Danuse Machackova', 'Female', 'Indian'),
('Male/face_467_White_3-9', 'Marcelina Krokosz', 'Male', 'White'),
('Male/face_468_Middle Eastern_3-9', 'Julian Ryfa', 'Male', 'Middle Eastern'),
('Male/face_469_Southeast Asian_3-9', 'Teodor Hruska', 'Male', 'Southeast Asian'),
('Female/face_470_Latino_Hispanic_10-19', 'Petra Ruzickova', 'Female', 'Latino_Hispanic'),
('Male/face_471_Middle Eastern_20-29', 'Michael Machacek', 'Male', 'Middle Eastern'),
('Female/face_472_East Asian_20-29', 'Balazs Danielne', 'Female', 'East Asian'),
('Male/face_473_White_40-49', 'Jan Riha', 'Male', 'White'),
('Female/face_474_White_20-29', 'Kveta Cerna', 'Female', 'White'),
('Female/face_475_White_20-29', 'Barbora Vlckova', 'Female', 'White'),
('Male/face_476_Latino_Hispanic_30-39', 'Papp Peter', 'Male', 'Latino_Hispanic'),
('Male/face_477_Indian_20-29', 'Miroslav Kubicek', 'Male', 'Indian'),
('Female/face_478_Latino_Hispanic_3-9', 'Bozena Jelinkova', 'Female', 'Latino_Hispanic'),
('Female/face_479_White_30-39', 'Kovacs Zsofia', 'Female', 'White'),
('Female/face_480_East Asian_50-59', 'Przemyslaw Pieszak', 'Female', 'East Asian'),
('Female/face_481_White_20-29', 'Artur Zimniak', 'Female', 'White'),
('Male/face_482_Middle Eastern_30-39', 'Adrian Sawko', 'Male', 'Middle Eastern'),
('Male/face_483_Latino_Hispanic_20-29', 'Arnost Machacek', 'Male', 'Latino_Hispanic'),
('Female/face_484_Black_10-19', 'Libuse Prochazkova', 'Female', 'Black'),
('Female/face_485_Indian_10-19', 'Drahoslava Vavrova', 'Female', 'Indian'),
('Female/face_486_Middle Eastern_30-39', 'Monika Balas', 'Female', 'Middle Eastern'),
('Female/face_487_Black_30-39', 'Agnieszka Dudzicz', 'Female', 'Black'),
('Female/face_488_Black_30-39', 'Urszula Kazior', 'Female', 'Black'),
('Female/face_489_East Asian_30-39', 'Sebastian Elwart', 'Female', 'East Asian'),
('Male/face_490_Middle Eastern_20-29', 'Tobiasz Tabak', 'Male', 'Middle Eastern'),
('Male/face_491_Black_30-39', 'Horymir Kraus', 'Male', 'Black'),
('Female/face_492_East Asian_10-19', 'Jaroslava Pavlikova', 'Female', 'East Asian'),
('Female/face_493_Latino_Hispanic_30-39', 'Robert Blank', 'Female', 'Latino_Hispanic'),
('Male/face_494_White_30-39', 'Gaja Hadam', 'Male', 'White'),
('Female/face_495_Southeast Asian_30-39', 'Nora Zakova', 'Female', 'Southeast Asian'),
('Female/face_496_East Asian_20-29', 'Kvetoslava Konecna', 'Female', 'East Asian'),
('Male/face_497_Latino_Hispanic_30-39', 'Vitezslav Nemecek', 'Male', 'Latino_Hispanic'),
('Female/face_498_East Asian_40-49', 'Emilie Fialova', 'Female', 'East Asian'),
('Male/face_499_Southeast Asian_40-49', 'Bruno Budzich', 'Male', 'Southeast Asian'),
('Male/face_500_White_3-9', 'Pavel Kolar', 'Male', 'White'),
('Female/face_501_White_0-2', 'Molnar Marta', 'Female', 'White'),
('Female/face_502_Latino_Hispanic_3-9', 'Dana Horackova', 'Female', 'Latino_Hispanic'),
('Female/face_503_East Asian_20-29', 'Monika Musilova', 'Female', 'East Asian'),
('Male/face_504_East Asian_3-9', 'Filip Brachaczek', 'Male', 'East Asian'),
('Female/face_505_Indian_0-2', 'Sebastian Romejko', 'Female', 'Indian'),
('Male/face_506_White_30-39', 'Vlasta Ruzicka', 'Male', 'White'),
('Female/face_507_Indian_3-9', 'Agata Brozova', 'Female', 'Indian'),
('Female/face_508_East Asian_10-19', 'Dominika Berankova', 'Female', 'East Asian'),
('Male/face_509_East Asian_3-9', 'Kiss Gyula', 'Male', 'East Asian'),
('Male/face_510_White_30-39', 'Emil Nemecek', 'Male', 'White'),
('Female/face_511_East Asian_10-19', 'Sarka Pavlikova', 'Female', 'East Asian'),
('Male/face_512_Southeast Asian_10-19', 'Mieszko Franc', 'Male', 'Southeast Asian'),
('Female/face_513_White_20-29', 'Hedvika Kasparova', 'Female', 'White'),
('Male/face_514_White_60-69', 'Antoni Blazejak', 'Male', 'White'),
('Male/face_515_Black_3-9', 'Hynek Kadlec', 'Male', 'Black'),
('Female/face_516_Black_10-19', 'Elena Kolarova', 'Female', 'Black'),
('Male/face_517_East Asian_3-9', 'Monika Nijak', 'Male', 'East Asian'),
('Female/face_518_Latino_Hispanic_20-29', 'Stanislava Kolarova', 'Female', 'Latino_Hispanic'),
('Male/face_519_White_20-29', 'Otakar Havel', 'Male', 'White'),
('Male/face_520_Latino_Hispanic_20-29', 'Szabo Zoltan', 'Male', 'Latino_Hispanic'),
('Male/face_521_Indian_20-29', 'Bohuslav Hajek', 'Male', 'Indian'),
('Female/face_522_White_20-29', 'Monika Pospisilova', 'Female', 'White'),
('Female/face_523_White_30-39', 'Sarka Jarosova', 'Female', 'White'),
('Male/face_524_Black_40-49', 'Emil Kopecky', 'Male', 'Black'),
('Female/face_525_Black_40-49', 'Marika Ochnio', 'Female', 'Black'),
('Male/face_526_Black_20-29', 'Kamil Zolnierczyk', 'Male', 'Black'),
('Male/face_527_White_30-39', 'Molnar Robert', 'Male', 'White'),
('Female/face_528_Southeast Asian_10-19', 'Horvath Sandorne', 'Female', 'Southeast Asian'),
('Female/face_529_Latino_Hispanic_20-29', 'Toth Csabane', 'Female', 'Latino_Hispanic'),
('Male/face_530_Black_3-9', 'Nagy Viktor', 'Male', 'Black'),
('Female/face_531_Latino_Hispanic_20-29', 'Miloslava Ticha', 'Female', 'Latino_Hispanic'),
('Female/face_532_Black_20-29', 'Jozef Dlugozima', 'Female', 'Black'),
('Male/face_533_Southeast Asian_40-49', 'Oskar Kliszcz', 'Male', 'Southeast Asian'),
('Female/face_534_Black_30-39', 'Lucie Maskova', 'Female', 'Black'),
('Male/face_535_East Asian_30-39', 'Orsos Zoltan', 'Male', 'East Asian'),
('Male/face_536_Middle Eastern_40-49', 'Kovacs Roland', 'Male', 'Middle Eastern'),
('Female/face_537_White_50-59', 'Veres Gergelyne', 'Female', 'White'),
('Male/face_538_East Asian_20-29', 'Ctirad Liska', 'Male', 'East Asian'),
('Male/face_539_Black_40-49', 'Aleksander Dulewicz', 'Male', 'Black'),
('Male/face_540_Latino_Hispanic_3-9', 'Bretislav Valenta', 'Male', 'Latino_Hispanic'),
('Male/face_541_Latino_Hispanic_30-39', 'Apolonia Kochman', 'Male', 'Latino_Hispanic'),
('Male/face_542_White_30-39', 'Lubomir Vlcek', 'Male', 'White'),
('Female/face_543_Indian_20-29', 'Apolena Hruba', 'Female', 'Indian'),
('Female/face_544_Latino_Hispanic_30-39', 'Adam Zuberek', 'Female', 'Latino_Hispanic'),
('Male/face_545_Indian_40-49', 'Radovan Barta', 'Male', 'Indian'),
('Male/face_546_Latino_Hispanic_30-39', 'Vit Cerny', 'Male', 'Latino_Hispanic'),
('Female/face_547_Southeast Asian_10-19', 'Adela Svobodova', 'Female', 'Southeast Asian'),
('Male/face_548_Latino_Hispanic_30-39', 'Alan Zimniak', 'Male', 'Latino_Hispanic'),
('Male/face_549_Latino_Hispanic_50-59', 'Ondrej Simek', 'Male', 'Latino_Hispanic'),
('Male/face_550_Latino_Hispanic_20-29', 'Kazimierz Molka', 'Male', 'Latino_Hispanic'),
('Male/face_551_Southeast Asian_40-49', 'Felix Urban', 'Male', 'Southeast Asian'),
('Male/face_552_White_20-29', 'Jaromir Prokop', 'Male', 'White'),
('Female/face_553_Indian_20-29', 'Milada Sedlackova', 'Female', 'Indian'),
('Male/face_554_White_50-59', 'Meszaros Zoltan', 'Male', 'White'),
('Male/face_555_Latino_Hispanic_60-69', 'Hubert Kozubal', 'Male', 'Latino_Hispanic'),
('Male/face_556_Latino_Hispanic_30-39', 'Nataniel Samulak', 'Male', 'Latino_Hispanic'),
('Male/face_557_Indian_3-9', 'Borivoj Stepanek', 'Male', 'Indian'),
('Female/face_558_White_30-39', 'Borys Wasek', 'Female', 'White'),
('Female/face_559_White_40-49', 'Klara Mikolajewicz', 'Female', 'White'),
('Male/face_560_White_0-2', 'Szalai Gabor', 'Male', 'White'),
('Female/face_561_Middle Eastern_30-39', 'Emil Czak', 'Female', 'Middle Eastern'),
('Female/face_562_White_10-19', 'Monika Svobodova', 'Female', 'White'),
('Female/face_563_Black_20-29', 'Alan Gierek', 'Female', 'Black'),
('Male/face_564_Black_30-39', 'Ludvik Nemec', 'Male', 'Black'),
('Female/face_565_East Asian_10-19', 'Sabina Simkova', 'Female', 'East Asian'),
('Female/face_566_Indian_50-59', 'Judita Bednarova', 'Female', 'Indian'),
('Female/face_567_White_30-39', 'Liwia Prasek', 'Female', 'White'),
('Male/face_568_Indian_50-59', 'Milos Valenta', 'Male', 'Indian'),
('Male/face_569_Middle Eastern_50-59', 'Rene Pospisil', 'Male', 'Middle Eastern'),
('Male/face_570_White_50-59', 'Rozalia Pazik', 'Male', 'White'),
('Male/face_571_Black_30-39', 'Vladimir Mares', 'Male', 'Black'),
('Male/face_572_Southeast Asian_3-9', 'Budai Milan', 'Male', 'Southeast Asian'),
('Female/face_573_Southeast Asian_3-9', 'Bozena Kopecka', 'Female', 'Southeast Asian'),
('Female/face_574_Middle Eastern_10-19', 'Alice Machova', 'Female', 'Middle Eastern'),
('Female/face_575_Latino_Hispanic_40-49', 'Eliza Karwan', 'Female', 'Latino_Hispanic'),
('Male/face_576_Latino_Hispanic_30-39', 'Krystian Golota', 'Male', 'Latino_Hispanic'),
('Male/face_577_White_30-39', 'Alois Prochazka', 'Male', 'White'),
('Male/face_578_Latino_Hispanic_3-9', 'Fryderyk Molak', 'Male', 'Latino_Hispanic'),
('Male/face_579_Indian_20-29', 'Patryk Petryk', 'Male', 'Indian'),
('Male/face_580_East Asian_3-9', 'Dawid Sierota', 'Male', 'East Asian'),
('Male/face_581_Southeast Asian_10-19', 'Michael Hruby', 'Male', 'Southeast Asian'),
('Female/face_582_East Asian_3-9', 'Agata Bartosova', 'Female', 'East Asian'),
('Male/face_583_East Asian_40-49', 'Rene Mach', 'Male', 'East Asian'),
('Male/face_584_Latino_Hispanic_10-19', 'Adam Kratochvil', 'Male', 'Latino_Hispanic'),
('Female/face_585_Black_20-29', 'Aleks Smoter', 'Female', 'Black'),
('Male/face_586_White_40-49', 'Nataniel Oleszko', 'Male', 'White'),
('Female/face_587_Indian_10-19', 'Lydie Horvathova', 'Female', 'Indian'),
('Female/face_588_Black_10-19', 'Racz Zsomborne', 'Female', 'Black'),
('Female/face_589_Southeast Asian_50-59', 'Michal Downar', 'Female', 'Southeast Asian'),
('Male/face_590_Latino_Hispanic_50-59', 'Jan Kycia', 'Male', 'Latino_Hispanic'),
('Male/face_591_Black_10-19', 'Milosz Bandyk', 'Male', 'Black'),
('Female/face_592_Latino_Hispanic_30-39', 'Liwia Bareja', 'Female', 'Latino_Hispanic'),
('Female/face_593_Latino_Hispanic_10-19', 'Svetlana Markova', 'Female', 'Latino_Hispanic'),
('Female/face_594_Black_30-39', 'Dorota Havlickova', 'Female', 'Black'),
('Female/face_595_Southeast Asian_3-9', 'Iveta Maskova', 'Female', 'Southeast Asian'),
('Male/face_596_Latino_Hispanic_40-49', 'Julita Labaj', 'Male', 'Latino_Hispanic'),
('Male/face_597_White_20-29', 'Filip Stejskal', 'Male', 'White'),
('Male/face_598_East Asian_3-9', 'Rudolf Muller', 'Male', 'East Asian'),
('Male/face_599_Indian_20-29', 'Borivoj Musil', 'Male', 'Indian'),
('Female/face_600_Southeast Asian_20-29', 'Alice Strnadova', 'Female', 'Southeast Asian'),
('Female/face_601_White_50-59', 'Zdenka Peskova', 'Female', 'White'),
('Female/face_602_Indian_20-29', 'Wiktor Kurys', 'Female', 'Indian'),
('Male/face_603_Latino_Hispanic_40-49', 'Alex Drwiega', 'Male', 'Latino_Hispanic'),
('Male/face_604_Black_30-39', 'Ludek Havlicek', 'Male', 'Black'),
('Female/face_605_Middle Eastern_20-29', 'Julian Glonek', 'Female', 'Middle Eastern'),
('Female/face_606_Southeast Asian_3-9', 'Damian Zackiewicz', 'Female', 'Southeast Asian'),
('Female/face_607_Latino_Hispanic_20-29', 'Apolena Mala', 'Female', 'Latino_Hispanic'),
('Male/face_608_Black_40-49', 'Kamil Juszczuk', 'Male', 'Black'),
('Male/face_609_Middle Eastern_40-49', 'Jaromir Blaha', 'Male', 'Middle Eastern'),
('Male/face_610_Middle Eastern_50-59', 'Bretislav Beran', 'Male', 'Middle Eastern'),
('Female/face_611_White_20-29', 'Horvath Annamaria', 'Female', 'White'),
('Male/face_612_Latino_Hispanic_20-29', 'Stefan Marek', 'Male', 'Latino_Hispanic'),
('Female/face_613_Latino_Hispanic_30-39', 'Cezary Jaskowiec', 'Female', 'Latino_Hispanic'),
('Female/face_614_East Asian_40-49', 'Maria Liskova', 'Female', 'East Asian'),
('Female/face_615_Indian_30-39', 'Marcel Behrendt', 'Female', 'Indian'),
('Male/face_616_Latino_Hispanic_40-49', 'Jan Fiala', 'Male', 'Latino_Hispanic'),
('Male/face_617_Southeast Asian_40-49', 'Maks Zawodnik', 'Male', 'Southeast Asian'),
('Female/face_618_East Asian_60-69', 'Radka Janeckova', 'Female', 'East Asian'),
('Female/face_619_Black_40-49', 'Stanislaw Domurad', 'Female', 'Black'),
('Male/face_620_Southeast Asian_10-19', 'Libor Svec', 'Male', 'Southeast Asian'),
('Female/face_621_Southeast Asian_20-29', 'Krzysztof Lodej', 'Female', 'Southeast Asian'),
('Female/face_622_East Asian_30-39', 'Marika Parda', 'Female', 'East Asian'),
('Female/face_623_Indian_30-39', 'Kamila Horackova', 'Female', 'Indian'),
('Female/face_624_Latino_Hispanic_20-29', 'Nemeth Zsofia', 'Female', 'Latino_Hispanic'),
('Male/face_625_Southeast Asian_20-29', 'Robert Stastny', 'Male', 'Southeast Asian'),
('Female/face_626_East Asian_20-29', 'Jacek Sztaba', 'Female', 'East Asian'),
('Female/face_627_Middle Eastern_30-39', 'Alice Berankova', 'Female', 'Middle Eastern'),
('Female/face_628_Southeast Asian_30-39', 'Marek Pusz', 'Female', 'Southeast Asian'),
('Female/face_629_Latino_Hispanic_40-49', 'Kiss Aniko', 'Female', 'Latino_Hispanic'),
('Female/face_630_Latino_Hispanic_30-39', 'Ida Skrzecz', 'Female', 'Latino_Hispanic'),
('Female/face_631_Southeast Asian_3-9', 'Molnar Adrienn', 'Female', 'Southeast Asian'),
('Male/face_632_Latino_Hispanic_10-19', 'Artur Lepa', 'Male', 'Latino_Hispanic'),
('Male/face_633_East Asian_20-29', 'Antoni Linke', 'Male', 'East Asian'),
('Male/face_634_Southeast Asian_3-9', 'Karel Holub', 'Male', 'Southeast Asian'),
('Female/face_635_Indian_20-29', 'Marcin Strzyz', 'Female', 'Indian'),
('Male/face_636_Latino_Hispanic_30-39', 'Szabo Jozsef', 'Male', 'Latino_Hispanic'),
('Female/face_637_East Asian_10-19', 'Sara Sedlackova', 'Female', 'East Asian'),
('Male/face_638_Latino_Hispanic_20-29', 'Magyar Levente', 'Male', 'Latino_Hispanic'),
('Female/face_639_White_20-29', 'Vanda Fialova', 'Female', 'White'),
('Male/face_640_East Asian_3-9', 'Artur Stejskal', 'Male', 'East Asian'),
('Male/face_641_Indian_20-29', 'Pavel Slavik', 'Male', 'Indian'),
('Male/face_642_Latino_Hispanic_30-39', 'Drahoslav Sedlacek', 'Male', 'Latino_Hispanic'),
('Male/face_643_White_30-39', 'Ida Trepczyk', 'Male', 'White'),
('Female/face_644_Black_20-29', 'Jakub Bujas', 'Female', 'Black'),
('Male/face_645_Latino_Hispanic_30-39', 'Alan Borkiewicz', 'Male', 'Latino_Hispanic'),
('Male/face_646_Middle Eastern_40-49', 'Lubos Beranek', 'Male', 'Middle Eastern'),
('Male/face_647_Middle Eastern_30-39', 'Vojtech Muller', 'Male', 'Middle Eastern'),
('Male/face_648_White_20-29', 'Otakar Nemecek', 'Male', 'White'),
('Female/face_649_Indian_10-19', 'Lydie Fialova', 'Female', 'Indian'),
('Female/face_650_Indian_40-49', 'Romana Navratilova', 'Female', 'Indian'),
('Female/face_651_White_30-39', 'Jeremi Ziajka', 'Female', 'White'),
('Female/face_652_East Asian_40-49', 'Miluse Cerna', 'Female', 'East Asian'),
('Male/face_653_Black_50-59', 'Robin Sedlak', 'Male', 'Black'),
('Male/face_654_Indian_10-19', 'Leonard Solarek', 'Male', 'Indian'),
('Male/face_655_White_30-39', 'Krystyna Grygorcewicz', 'Male', 'White'),
('Male/face_656_Latino_Hispanic_30-39', 'Nicole Dubik', 'Male', 'Latino_Hispanic'),
('Male/face_657_Indian_30-39', 'Urszula Wichary', 'Male', 'Indian'),
('Male/face_658_Latino_Hispanic_50-59', 'Tomasz Steuer', 'Male', 'Latino_Hispanic'),
('Male/face_659_East Asian_3-9', 'Hubert Beran', 'Male', 'East Asian'),
('Female/face_660_Southeast Asian_30-39', 'Johana Pospisilova', 'Female', 'Southeast Asian'),
('Female/face_661_White_40-49', 'Simona Prochazkova', 'Female', 'White'),
('Male/face_662_White_30-39', 'Ignacy Lenda', 'Male', 'White'),
('Male/face_663_Latino_Hispanic_10-19', 'Angelika Aleksander', 'Male', 'Latino_Hispanic'),
('Female/face_664_White_20-29', 'Pavlina Kopecka', 'Female', 'White'),
('Female/face_665_White_30-39', 'Miloslava Blahova', 'Female', 'White'),
('Male/face_666_White_20-29', 'Ales Vacek', 'Male', 'White'),
('Male/face_667_Middle Eastern_30-39', 'Ignacy Wiatrak', 'Male', 'Middle Eastern'),
('Male/face_668_Middle Eastern_40-49', 'Hynek Stanek', 'Male', 'Middle Eastern'),
('Male/face_669_Indian_20-29', 'Alexander Kaspar', 'Male', 'Indian'),
('Male/face_670_Latino_Hispanic_50-59', 'Bruno Klinger', 'Male', 'Latino_Hispanic'),
('Male/face_671_White_30-39', 'Lubomir Svoboda', 'Male', 'White'),
('Female/face_672_Indian_20-29', 'Kristina Kolarova', 'Female', 'Indian'),
('Male/face_673_Southeast Asian_3-9', 'Aurelia Uroda', 'Male', 'Southeast Asian'),
('Female/face_674_Black_40-49', 'Fabian Gasienica', 'Female', 'Black'),
('Male/face_675_Indian_50-59', 'Richard Slavik', 'Male', 'Indian'),
('Male/face_676_Indian_30-39', 'Ales Stastny', 'Male', 'Indian'),
('Female/face_677_Latino_Hispanic_50-59', 'Elena Jarosova', 'Female', 'Latino_Hispanic'),
('Male/face_678_Middle Eastern_40-49', 'Radomir Barta', 'Male', 'Middle Eastern'),
('Female/face_679_Black_10-19', 'Kveta Kasparova', 'Female', 'Black'),
('Female/face_680_Southeast Asian_20-29', 'Dagmar Pavlikova', 'Female', 'Southeast Asian'),
('Female/face_681_Latino_Hispanic_20-29', 'Ester Matouskova', 'Female', 'Latino_Hispanic'),
('Female/face_682_Southeast Asian_20-29', 'Vera Vankova', 'Female', 'Southeast Asian'),
('Female/face_683_Black_40-49', 'Andela Fiserova', 'Female', 'Black'),
('Female/face_684_Southeast Asian_30-39', 'Vilma Fialova', 'Female', 'Southeast Asian'),
('Female/face_685_Latino_Hispanic_10-19', 'Cyprian Bany', 'Female', 'Latino_Hispanic'),
('Female/face_686_White_30-39', 'Danuse Maskova', 'Female', 'White'),
('Male/face_687_Southeast Asian_20-29', 'Feher Zoltan', 'Male', 'Southeast Asian'),
('Female/face_688_Latino_Hispanic_10-19', 'Nina Jelinkova', 'Female', 'Latino_Hispanic'),
('Female/face_689_White_40-49', 'Sarka Mullerova', 'Female', 'White'),
('Male/face_690_White_50-59', 'Nagy Jozsef', 'Male', 'White'),
('Male/face_691_East Asian_20-29', 'Albert Pokorny', 'Male', 'East Asian'),
('Male/face_692_Middle Eastern_20-29', 'Olah Gergely', 'Male', 'Middle Eastern'),
('Female/face_693_Middle Eastern_40-49', 'Jirina Berankova', 'Female', 'Middle Eastern'),
('Male/face_694_Indian_40-49', 'Marek Jezek', 'Male', 'Indian'),
('Male/face_695_Middle Eastern_20-29', 'Libor Jelinek', 'Male', 'Middle Eastern'),
('Male/face_696_Latino_Hispanic_40-49', 'Simon Tuma', 'Male', 'Latino_Hispanic'),
('Female/face_697_White_10-19', 'Ida Dziewit', 'Female', 'White'),
('Male/face_698_White_40-49', 'Oskar Darul', 'Male', 'White'),
('Female/face_699_Southeast Asian_30-39', 'Alexandra Kralova', 'Female', 'Southeast Asian'),
('Male/face_700_Indian_40-49', 'Jedrzej Trepka', 'Male', 'Indian'),
('Male/face_701_Black_30-39', 'Horvath Gabor', 'Male', 'Black'),
('Female/face_702_Latino_Hispanic_3-9', 'Mahulena Stejskalova', 'Female', 'Latino_Hispanic'),
('Female/face_703_East Asian_10-19', 'Anezka Jarosova', 'Female', 'East Asian'),
('Male/face_704_Middle Eastern_20-29', 'Vlastimil Navratil', 'Male', 'Middle Eastern'),
('Male/face_705_White_20-29', 'Radek Maly', 'Male', 'White'),
('Female/face_706_Southeast Asian_30-39', 'Viktorie Liskova', 'Female', 'Southeast Asian'),
('Male/face_707_Latino_Hispanic_20-29', 'Ondrej Sedlacek', 'Male', 'Latino_Hispanic'),
('Male/face_708_Middle Eastern_40-49', 'Norbert Strnad', 'Male', 'Middle Eastern'),
('Male/face_709_Latino_Hispanic_40-49', 'Miroslav Liska', 'Male', 'Latino_Hispanic'),
('Female/face_710_White_20-29', 'Aleks Melaniuk', 'Female', 'White'),
('Male/face_711_White_40-49', 'Kiss Jozsef', 'Male', 'White'),
('Female/face_712_Middle Eastern_20-29', 'Lakatos Bianka', 'Female', 'Middle Eastern'),
('Female/face_713_Black_60-69', 'Stefan Dzieza', 'Female', 'Black'),
('Male/face_714_Indian_30-39', 'Cyprian Brach', 'Male', 'Indian'),
('Male/face_715_Latino_Hispanic_10-19', 'Toth Istvan', 'Male', 'Latino_Hispanic'),
('Male/face_716_White_20-29', 'Arnost Liska', 'Male', 'White'),
('Male/face_717_Middle Eastern_more than 70', 'Mikulas Novotny', 'Male', 'Middle Eastern'),
('Male/face_718_White_20-29', 'Jan Vlcek', 'Male', 'White'),
('Female/face_719_Southeast Asian_more than 70', 'Silvie Cermakova', 'Female', 'Southeast Asian'),
('Male/face_720_East Asian_30-39', 'David Kriz', 'Male', 'East Asian'),
('Female/face_721_Black_3-9', 'Marcela Blahova', 'Female', 'Black'),
('Female/face_722_White_20-29', 'Slavena Krausova', 'Female', 'White'),
('Male/face_723_Middle Eastern_3-9', 'Lubos Polak', 'Male', 'Middle Eastern'),
('Female/face_724_White_0-2', 'Romana Stastna', 'Female', 'White'),
('Male/face_725_White_3-9', 'Julian Bobik', 'Male', 'White'),
('Female/face_726_Middle Eastern_10-19', 'Lada Horvathova', 'Female', 'Middle Eastern'),
('Female/face_727_Southeast Asian_30-39', 'Stefan Derek', 'Female', 'Southeast Asian'),
('Male/face_728_Indian_20-29', 'Vaclav Toman', 'Male', 'Indian'),
('Female/face_729_Latino_Hispanic_60-69', 'Miluse Vavrova', 'Female', 'Latino_Hispanic'),
('Male/face_730_Southeast Asian_10-19', 'Lakatos Arpad', 'Male', 'Southeast Asian'),
('Female/face_731_Indian_20-29', 'Zora Horakova', 'Female', 'Indian'),
('Female/face_732_Indian_20-29', 'Iveta Polakova', 'Female', 'Indian'),
('Male/face_733_Indian_20-29', 'Vlasta Toman', 'Male', 'Indian'),
('Male/face_734_East Asian_0-2', 'Blahoslav Kraus', 'Male', 'East Asian'),
('Male/face_735_White_20-29', 'Zdenek Havlicek', 'Male', 'White'),
('Female/face_736_Indian_3-9', 'Krzysztof Kamyszek', 'Female', 'Indian'),
('Male/face_737_Latino_Hispanic_40-49', 'Bruno Koczara', 'Male', 'Latino_Hispanic'),
('Female/face_738_Black_20-29', 'Aurelia Cyba', 'Female', 'Black'),
('Female/face_739_Black_20-29', 'Vlasta Liskova', 'Female', 'Black'),
('Female/face_740_Latino_Hispanic_10-19', 'Damian Dulas', 'Female', 'Latino_Hispanic'),
('Male/face_741_Middle Eastern_40-49', 'Tobiasz Pilipczuk', 'Male', 'Middle Eastern'),
('Male/face_742_White_40-49', 'Ivo Stastny', 'Male', 'White'),
('Male/face_743_White_40-49', 'Rostislav Hruby', 'Male', 'White'),
('Female/face_744_Southeast Asian_20-29', 'Urszula Lica', 'Female', 'Southeast Asian'),
('Female/face_745_Latino_Hispanic_40-49', 'Daniela Fiserova', 'Female', 'Latino_Hispanic'),
('Male/face_746_Indian_3-9', 'Vasyl Liska', 'Male', 'Indian'),
('Female/face_747_East Asian_20-29', 'Franciszek Ros', 'Female', 'East Asian'),
('Female/face_748_Black_20-29', 'Stanislava Jandova', 'Female', 'Black'),
('Male/face_749_Latino_Hispanic_3-9', 'Marcel Kanik', 'Male', 'Latino_Hispanic'),
('Male/face_750_White_3-9', 'Molnar Gyula', 'Male', 'White'),
('Male/face_751_Southeast Asian_10-19', 'Maciej Prucnal', 'Male', 'Southeast Asian'),
('Female/face_752_East Asian_20-29', 'Melania Mydlak', 'Female', 'East Asian'),
('Male/face_753_Middle Eastern_10-19', 'Peter Beran', 'Male', 'Middle Eastern'),
('Female/face_754_Indian_60-69', 'Kacper Kosidlo', 'Female', 'Indian'),
('Male/face_755_Black_3-9', 'Ladislav Blazek', 'Male', 'Black'),
('Female/face_756_Indian_0-2', 'Malwina Jas', 'Female', 'Indian'),
('Female/face_757_East Asian_20-29', 'Melania Mirocha', 'Female', 'East Asian'),
('Male/face_758_Indian_3-9', 'Fryderyk Kusmider', 'Male', 'Indian'),
('Female/face_759_Latino_Hispanic_30-39', 'Zora Bednarova', 'Female', 'Latino_Hispanic'),
('Male/face_760_East Asian_30-39', 'Vasyl Zak', 'Male', 'East Asian'),
('Male/face_761_Black_30-39', 'Horymir Holub', 'Male', 'Black'),
('Female/face_762_White_20-29', 'Iva Jelinkova', 'Female', 'White'),
('Male/face_763_White_30-39', 'Bohuslav Vlcek', 'Male', 'White'),
('Female/face_764_Middle Eastern_30-39', 'Nikola Cerna', 'Female', 'Middle Eastern'),
('Female/face_765_White_10-19', 'Tymon Sypien', 'Female', 'White'),
('Male/face_766_East Asian_20-29', 'Nagy Endre', 'Male', 'East Asian'),
('Male/face_767_White_50-59', 'Petr Polak', 'Male', 'White'),
('Female/face_768_Middle Eastern_30-39', 'Borys Wichlacz', 'Female', 'Middle Eastern'),
('Male/face_769_Latino_Hispanic_20-29', 'Peter Janda', 'Male', 'Latino_Hispanic'),
('Female/face_770_Latino_Hispanic_60-69', 'Mariusz Osiadacz', 'Female', 'Latino_Hispanic'),
('Male/face_771_East Asian_20-29', 'Ivan Pavlicek', 'Male', 'East Asian'),
('Female/face_772_Middle Eastern_10-19', 'Sebastian Wons', 'Female', 'Middle Eastern'),
('Female/face_773_Latino_Hispanic_20-29', 'Szabo Maria', 'Female', 'Latino_Hispanic'),
('Male/face_774_Latino_Hispanic_10-19', 'Radovan Bilek', 'Male', 'Latino_Hispanic'),
('Male/face_775_Black_30-39', 'Libor Pokorny', 'Male', 'Black'),
('Male/face_776_Black_20-29', 'Lukasz Langiewicz', 'Male', 'Black'),
('Female/face_777_Latino_Hispanic_3-9', 'Zaneta Kratochvilova', 'Female', 'Latino_Hispanic'),
('Male/face_778_Middle Eastern_20-29', 'Zbynek Benes', 'Male', 'Middle Eastern'),
('Male/face_779_Black_30-39', 'Ignac Havel', 'Male', 'Black'),
('Male/face_780_Latino_Hispanic_30-39', 'Bakos Daniel', 'Male', 'Latino_Hispanic'),
('Male/face_781_Latino_Hispanic_50-59', 'Vladimir Tuma', 'Male', 'Latino_Hispanic'),
('Male/face_782_Black_50-59', 'Bretislav Svoboda', 'Male', 'Black'),
('Male/face_783_White_20-29', 'Dawid Sztuba', 'Male', 'White'),
('Female/face_784_White_20-29', 'Jindriska Mala', 'Female', 'White'),
('Male/face_785_East Asian_20-29', 'Ewa Kus', 'Male', 'East Asian'),
('Male/face_786_Indian_40-49', 'Svatopluk Marek', 'Male', 'Indian'),
('Female/face_787_White_30-39', 'Aneta Matejkova', 'Female', 'White'),
('Male/face_788_Indian_40-49', 'Szabo Karoly', 'Male', 'Indian'),
('Male/face_789_Black_20-29', 'Toth Csaba', 'Male', 'Black'),
('Female/face_790_White_3-9', 'Blazej Kobryn', 'Female', 'White'),
('Female/face_791_White_30-39', 'Renata Kasparova', 'Female', 'White'),
('Female/face_792_Southeast Asian_30-39', 'Gustaw Bojdo', 'Female', 'Southeast Asian'),
('Male/face_793_White_20-29', 'Kalina Humeniuk', 'Male', 'White'),
('Male/face_794_Black_3-9', 'Ctibor Strnad', 'Male', 'Black'),
('Male/face_795_Southeast Asian_30-39', 'Horvath Krisztian', 'Male', 'Southeast Asian'),
('Female/face_796_Latino_Hispanic_20-29', 'Przemyslaw Leszcz', 'Female', 'Latino_Hispanic'),
('Female/face_797_Latino_Hispanic_30-39', 'Nina Hruskova', 'Female', 'Latino_Hispanic'),
('Male/face_798_Southeast Asian_50-59', 'Horvath Bence', 'Male', 'Southeast Asian'),
('Male/face_799_Black_3-9', 'Kovacs Laszlo', 'Male', 'Black'),
('Male/face_800_Black_50-59', 'Gustaw Pierchala', 'Male', 'Black'),
('Female/face_801_Black_10-19', 'Nemeth Imrene', 'Female', 'Black'),
('Female/face_802_Black_30-39', 'Eliska Soukupova', 'Female', 'Black'),
('Male/face_803_East Asian_10-19', 'Ada Mytych', 'Male', 'East Asian'),
('Male/face_804_White_3-9', 'Jiri Bartos', 'Male', 'White'),
('Male/face_805_White_30-39', 'Budai Istvan', 'Male', 'White'),
('Female/face_806_White_10-19', 'Frantiska Soukupova', 'Female', 'White'),
('Male/face_807_East Asian_20-29', 'Fryderyk Brodka', 'Male', 'East Asian'),
('Female/face_808_East Asian_20-29', 'Major Jozsefne', 'Female', 'East Asian'),
('Male/face_809_East Asian_40-49', 'Arnost Blazek', 'Male', 'East Asian'),
('Female/face_810_Latino_Hispanic_60-69', 'Bianka Komsta', 'Female', 'Latino_Hispanic'),
('Male/face_811_Middle Eastern_40-49', 'Miloslav Tuma', 'Male', 'Middle Eastern'),
('Male/face_812_Latino_Hispanic_50-59', 'Ada Myrcik', 'Male', 'Latino_Hispanic'),
('Male/face_813_White_30-39', 'Dariusz Gronkiewicz', 'Male', 'White'),
('Female/face_814_Indian_20-29', 'Silvie Svobodova', 'Female', 'Indian'),
('Male/face_815_Indian_3-9', 'Krystian Korniak', 'Male', 'Indian'),
('Male/face_816_Southeast Asian_40-49', 'Albert Beranek', 'Male', 'Southeast Asian'),
('Male/face_817_Indian_30-39', 'Robin Tesar', 'Male', 'Indian'),
('Female/face_818_East Asian_50-59', 'Vera Rihova', 'Female', 'East Asian'),
('Male/face_819_White_20-29', 'Jaroslav Strnad', 'Male', 'White'),
('Male/face_820_Black_40-49', 'Kacper Ludwisiak', 'Male', 'Black'),
('Female/face_821_Middle Eastern_20-29', 'Stepanka Dvorakova', 'Female', 'Middle Eastern'),
('Female/face_822_White_10-19', 'Tymoteusz Tarach', 'Female', 'White'),
('Male/face_823_White_50-59', 'Marian Svoboda', 'Male', 'White'),
('Female/face_824_Latino_Hispanic_3-9', 'Urszula Janoszka', 'Female', 'Latino_Hispanic'),
('Male/face_825_East Asian_40-49', 'Marcin Sommer', 'Male', 'East Asian'),
('Male/face_826_White_30-39', 'Ignac Cermak', 'Male', 'White'),
('Male/face_827_Black_30-39', 'Ignac Dvorak', 'Male', 'Black'),
('Female/face_828_Middle Eastern_30-39', 'Ewelina Mieloch', 'Female', 'Middle Eastern'),
('Female/face_829_Black_3-9', 'Ivana Sevcikova', 'Female', 'Black'),
('Female/face_830_Black_20-29', 'Blanka Sadura', 'Female', 'Black'),
('Female/face_831_Southeast Asian_20-29', 'Oliwier Kazana', 'Female', 'Southeast Asian'),
('Male/face_832_East Asian_3-9', 'Ignacy Prystupa', 'Male', 'East Asian'),
('Male/face_833_Southeast Asian_20-29', 'Jan Kopecky', 'Male', 'Southeast Asian'),
('Female/face_834_Latino_Hispanic_20-29', 'Roksana Klek', 'Female', 'Latino_Hispanic'),
('Male/face_835_Southeast Asian_3-9', 'Miroslav Dvorak', 'Male', 'Southeast Asian'),
('Female/face_836_Latino_Hispanic_40-49', 'Vera Konecna', 'Female', 'Latino_Hispanic'),
('Female/face_837_White_20-29', 'Kajetan Liss', 'Female', 'White'),
('Male/face_838_Middle Eastern_30-39', 'Aniela Prokopczyk', 'Male', 'Middle Eastern'),
('Male/face_839_Middle Eastern_3-9', 'Vratislav Tuma', 'Male', 'Middle Eastern'),
('Male/face_840_Black_40-49', 'Melania Pyzel', 'Male', 'Black'),
('Male/face_841_Black_3-9', 'Leon Peciak', 'Male', 'Black'),
('Male/face_842_Indian_50-59', 'Igor Skup', 'Male', 'Indian'),
('Male/face_843_White_10-19', 'Apolonia Strama', 'Male', 'White'),
('Female/face_844_White_3-9', 'Gabriel Dlubak', 'Female', 'White'),
('Male/face_845_Indian_40-49', 'Dorota Sapeta', 'Male', 'Indian'),
('Female/face_846_Latino_Hispanic_3-9', 'Olgierd Bystrek', 'Female', 'Latino_Hispanic'),
('Female/face_847_White_10-19', 'Igor Surmiak', 'Female', 'White'),
('Female/face_848_Black_20-29', 'Anita Neubauer', 'Female', 'Black'),
('Female/face_849_Indian_3-9', 'Viktorie Sevcikova', 'Female', 'Indian'),
('Male/face_850_Black_20-29', 'Nela Szymonik', 'Male', 'Black'),
('Female/face_851_Black_20-29', 'Radoslaw Rogal', 'Female', 'Black'),
('Male/face_852_Middle Eastern_10-19', 'Ctibor Jaros', 'Male', 'Middle Eastern'),
('Female/face_853_Indian_30-39', 'Romana Jelinkova', 'Female', 'Indian'),
('Male/face_854_Indian_20-29', 'Kamil Kubicek', 'Male', 'Indian'),
('Male/face_855_Middle Eastern_40-49', 'Artur Kucera', 'Male', 'Middle Eastern'),
('Female/face_856_East Asian_60-69', 'Eryk Dziwak', 'Female', 'East Asian'),
('Male/face_857_Indian_40-49', 'Roksana Pazdan', 'Male', 'Indian'),
('Male/face_858_Latino_Hispanic_30-39', 'Mikulas Vitek', 'Male', 'Latino_Hispanic'),
('Male/face_859_Middle Eastern_30-39', 'Mariusz Krystkowiak', 'Male', 'Middle Eastern'),
('Male/face_860_Indian_30-39', 'Vratislav Zeman', 'Male', 'Indian'),
('Male/face_861_Middle Eastern_30-39', 'Dariusz Waniek', 'Male', 'Middle Eastern'),
('Female/face_862_Indian_40-49', 'Zdenka Ruzickova', 'Female', 'Indian'),
('Female/face_863_East Asian_30-39', 'Martina Zakova', 'Female', 'East Asian'),
('Male/face_864_Black_10-19', 'Denis Stepanek', 'Male', 'Black'),
('Female/face_865_White_20-29', 'Hubert Mol', 'Female', 'White'),
('Male/face_866_Indian_40-49', 'Marcelina Franc', 'Male', 'Indian'),
('Female/face_867_Indian_0-2', 'Marie Kadlecova', 'Female', 'Indian'),
('Female/face_868_Indian_40-49', 'Lenka Mala', 'Female', 'Indian'),
('Female/face_869_Black_30-39', 'Barbora Vitkova', 'Female', 'Black'),
('Female/face_870_Southeast Asian_3-9', 'Malwina Ledzion', 'Female', 'Southeast Asian'),
('Female/face_871_Latino_Hispanic_20-29', 'Mahulena Fiserova', 'Female', 'Latino_Hispanic'),
('Female/face_872_Southeast Asian_10-19', 'Anna Pospisilova', 'Female', 'Southeast Asian'),
('Female/face_873_White_20-29', 'Konrad Kolesnik', 'Female', 'White'),
('Female/face_874_Indian_20-29', 'Sona Pavlikova', 'Female', 'Indian'),
('Male/face_875_Southeast Asian_3-9', 'Radek Moravec', 'Male', 'Southeast Asian'),
('Female/face_876_Southeast Asian_20-29', 'Tomasz Kukiela', 'Female', 'Southeast Asian'),
('Male/face_877_Black_3-9', 'Simon Pokorny', 'Male', 'Black'),
('Male/face_878_Indian_30-39', 'Michal Kopecky', 'Male', 'Indian'),
('Female/face_879_Black_20-29', 'Zofie Vankova', 'Female', 'Black'),
('Female/face_880_East Asian_50-59', 'Martina Svecova', 'Female', 'East Asian'),
('Female/face_881_Middle Eastern_50-59', 'Filip Such', 'Female', 'Middle Eastern'),
('Female/face_882_Black_50-59', 'Tomasz Prygiel', 'Female', 'Black'),
('Female/face_883_Southeast Asian_3-9', 'Adela Urbanova', 'Female', 'Southeast Asian'),
('Female/face_884_Indian_60-69', 'Ester Kovarova', 'Female', 'Indian'),
('Female/face_885_White_40-49', 'Gaja Jancewicz', 'Female', 'White'),
('Male/face_886_Southeast Asian_30-39', 'Vladislav Kubicek', 'Male', 'Southeast Asian'),
('Female/face_887_Black_10-19', 'Maksymilian Raczkiewicz', 'Female', 'Black'),
('Male/face_888_Indian_20-29', 'Marcin Niewola', 'Male', 'Indian'),
('Male/face_889_White_60-69', 'Jozef Fiala', 'Male', 'White'),
('Female/face_890_Middle Eastern_40-49', 'Miloslava Moravcova', 'Female', 'Middle Eastern'),
('Male/face_891_Indian_10-19', 'Arnost Mach', 'Male', 'Indian'),
('Male/face_892_Latino_Hispanic_3-9', 'Cyprian Durlak', 'Male', 'Latino_Hispanic'),
('Male/face_893_Latino_Hispanic_40-49', 'Robin Polak', 'Male', 'Latino_Hispanic'),
('Female/face_894_Latino_Hispanic_20-29', 'Piotr Patora', 'Female', 'Latino_Hispanic'),
('Male/face_895_White_40-49', 'Sandra Wazny', 'Male', 'White'),
('Female/face_896_Black_40-49', 'Nela Kadlecova', 'Female', 'Black'),
('Male/face_897_Latino_Hispanic_3-9', 'Toth Laszlo', 'Male', 'Latino_Hispanic'),
('Male/face_898_White_40-49', 'Frantisek Prokop', 'Male', 'White'),
('Female/face_899_Latino_Hispanic_40-49', 'Kristina Krizova', 'Female', 'Latino_Hispanic'),
('Female/face_900_Black_20-29', 'Marcelina Labno', 'Female', 'Black'),
('Male/face_901_Southeast Asian_3-9', 'Hubert Kadlec', 'Male', 'Southeast Asian'),
('Male/face_902_White_40-49', 'Piotr Golon', 'Male', 'White'),
('Male/face_903_Latino_Hispanic_30-39', 'Ferdinand Novak', 'Male', 'Latino_Hispanic'),
('Male/face_904_Latino_Hispanic_30-39', 'Jiri Fiser', 'Male', 'Latino_Hispanic'),
('Female/face_905_Southeast Asian_40-49', 'Johana Stepankova', 'Female', 'Southeast Asian'),
('Male/face_906_Southeast Asian_30-39', 'Ewa Budych', 'Male', 'Southeast Asian'),
('Female/face_907_Middle Eastern_10-19', 'Anita Bastek', 'Female', 'Middle Eastern'),
('Female/face_908_White_30-39', 'Andrea Brozova', 'Female', 'White'),
('Female/face_909_East Asian_20-29', 'Slavena Kopecka', 'Female', 'East Asian'),
('Male/face_910_Black_30-39', 'Alan Korgul', 'Male', 'Black'),
('Male/face_911_Indian_3-9', 'Alex Posmyk', 'Male', 'Indian'),
('Male/face_912_Latino_Hispanic_20-29', 'Eduard Strnad', 'Male', 'Latino_Hispanic'),
('Male/face_913_White_40-49', 'Apolonia Baster', 'Male', 'White'),
('Male/face_914_Latino_Hispanic_40-49', 'Bohumil Kucera', 'Male', 'Latino_Hispanic'),
('Female/face_915_White_40-49', 'Norbert Pupek', 'Female', 'White'),
('Female/face_916_Latino_Hispanic_60-69', 'Michal Karczmarek', 'Female', 'Latino_Hispanic'),
('Female/face_917_White_20-29', 'Magdalena Zakova', 'Female', 'White'),
('Female/face_918_Black_20-29', 'Ladislava Hruskova', 'Female', 'Black'),
('Male/face_919_Black_3-9', 'Zbynek Janda', 'Male', 'Black'),
('Female/face_920_Latino_Hispanic_50-59', 'Natalie Markova', 'Female', 'Latino_Hispanic'),
('Male/face_921_Black_3-9', 'Roza Fraczkiewicz', 'Male', 'Black'),
('Male/face_922_Black_30-39', 'Hubert Kral', 'Male', 'Black'),
('Female/face_923_Southeast Asian_3-9', 'Blazej Mieloch', 'Female', 'Southeast Asian'),
('Male/face_924_White_40-49', 'Rostislav Kucera', 'Male', 'White'),
('Male/face_925_Southeast Asian_30-39', 'Libor Machacek', 'Male', 'Southeast Asian'),
('Male/face_926_Latino_Hispanic_20-29', 'Dominik Dolezal', 'Male', 'Latino_Hispanic'),
('Male/face_927_Latino_Hispanic_40-49', 'Filip Sykora', 'Male', 'Latino_Hispanic'),
('Male/face_928_Latino_Hispanic_50-59', 'Lubos Mares', 'Male', 'Latino_Hispanic'),
('Female/face_929_Latino_Hispanic_20-29', 'Marcin Bernatek', 'Female', 'Latino_Hispanic'),
('Male/face_930_White_10-19', 'Zikmund Benes', 'Male', 'White'),
('Female/face_931_White_30-39', 'Natalie Hruba', 'Female', 'White'),
('Female/face_932_White_10-19', 'Zdenka Krizova', 'Female', 'White'),
('Female/face_933_Latino_Hispanic_20-29', 'Vanda Kovarova', 'Female', 'Latino_Hispanic'),
('Male/face_934_Indian_50-59', 'Maurycy Dyszkiewicz', 'Male', 'Indian'),
('Female/face_935_Southeast Asian_20-29', 'Mieszko Ciuk', 'Female', 'Southeast Asian'),
('Female/face_936_Latino_Hispanic_50-59', 'Stepanka Krausova', 'Female', 'Latino_Hispanic'),
('Male/face_937_East Asian_3-9', 'Mariusz Zygula', 'Male', 'East Asian'),
('Male/face_938_Indian_30-39', 'Vit Zak', 'Male', 'Indian'),
('Female/face_939_White_30-39', 'Kristyna Pospisilova', 'Female', 'White'),
('Female/face_940_East Asian_30-39', 'Jaroslava Novotna', 'Female', 'East Asian'),
('Male/face_941_Black_3-9', 'Krystof Machacek', 'Male', 'Black'),
('Female/face_942_East Asian_20-29', 'Linda Vitkova', 'Female', 'East Asian'),
('Female/face_943_Southeast Asian_60-69', 'Dorota Vavrova', 'Female', 'Southeast Asian'),
('Male/face_944_Southeast Asian_30-39', 'Vladimir Dvorak', 'Male', 'Southeast Asian'),
('Male/face_945_Black_3-9', 'Drahoslav Stastny', 'Male', 'Black'),
('Female/face_946_Black_3-9', 'Sona Maresova', 'Female', 'Black'),
('Female/face_947_White_10-19', 'Szabo Gabriella', 'Female', 'White'),
('Female/face_948_East Asian_30-39', 'Judita Peskova', 'Female', 'East Asian'),
('Male/face_949_White_20-29', 'Ksawery Szczudlo', 'Male', 'White'),
('Male/face_950_Middle Eastern_50-59', 'Matous Pavlicek', 'Male', 'Middle Eastern'),
('Male/face_951_Latino_Hispanic_40-49', 'Ignac Liska', 'Male', 'Latino_Hispanic'),
('Male/face_952_Black_3-9', 'Maks Wojak', 'Male', 'Black'),
('Male/face_953_Middle Eastern_40-49', 'Jindrich Maly', 'Male', 'Middle Eastern'),
('Female/face_954_Latino_Hispanic_20-29', 'Ivona Sevcikova', 'Female', 'Latino_Hispanic'),
('Male/face_955_Middle Eastern_3-9', 'Ferdinand Vlcek', 'Male', 'Middle Eastern'),
('Female/face_956_Latino_Hispanic_30-39', 'Kristyna Ticha', 'Female', 'Latino_Hispanic'),
('Female/face_957_Southeast Asian_3-9', 'Norbert Dargacz', 'Female', 'Southeast Asian'),
('Female/face_958_Black_60-69', 'Tymoteusz Kruzel', 'Female', 'Black'),
('Male/face_959_Black_30-39', 'Stanislaw Swiadek', 'Male', 'Black'),
('Male/face_960_Latino_Hispanic_20-29', 'Rozalia Tworzydlo', 'Male', 'Latino_Hispanic'),
('Male/face_961_White_40-49', 'Igor Soukup', 'Male', 'White'),
('Male/face_962_East Asian_3-9', 'Milan Masek', 'Male', 'East Asian'),
('Male/face_963_Middle Eastern_40-49', 'Artur Slavik', 'Male', 'Middle Eastern'),
('Female/face_964_White_0-2', 'Apolena Kratochvilova', 'Female', 'White'),
('Male/face_965_Indian_40-49', 'Dagmara Robaszkiewicz', 'Male', 'Indian'),
('Female/face_966_Black_40-49', 'Tadeusz Kunysz', 'Female', 'Black'),
('Female/face_967_Middle Eastern_20-29', 'Radka Vankova', 'Female', 'Middle Eastern'),
('Male/face_968_Southeast Asian_40-49', 'Radomir Pavlicek', 'Male', 'Southeast Asian'),
('Female/face_969_Southeast Asian_20-29', 'Adrianna Strawa', 'Female', 'Southeast Asian'),
('Male/face_970_East Asian_30-39', 'Oskar Prokopczyk', 'Male', 'East Asian'),
('Male/face_971_Southeast Asian_30-39', 'Miroslav Urban', 'Male', 'Southeast Asian'),
('Male/face_972_East Asian_10-19', 'Krystof Cerny', 'Male', 'East Asian'),
('Female/face_973_Black_30-39', 'Eva Liskova', 'Female', 'Black'),
('Male/face_974_Indian_3-9', 'Tomas Mares', 'Male', 'Indian'),
('Female/face_975_Black_50-59', 'Jindriska Horakova', 'Female', 'Black'),
('Male/face_976_Middle Eastern_3-9', 'Tomas Moravec', 'Male', 'Middle Eastern'),
('Female/face_977_East Asian_20-29', 'Martina Matejkova', 'Female', 'East Asian'),
('Male/face_978_White_20-29', 'Vit Novotny', 'Male', 'White'),
('Female/face_979_Latino_Hispanic_20-29', 'Radoslaw Sypek', 'Female', 'Latino_Hispanic'),
('Female/face_980_Black_3-9', 'Vilma Markova', 'Female', 'Black'),
('Male/face_981_Black_30-39', 'Gustaw Gradek', 'Male', 'Black'),
('Female/face_982_Indian_10-19', 'Pavlina Vlckova', 'Female', 'Indian'),
('Female/face_983_Indian_20-29', 'Martina Machova', 'Female', 'Indian'),
('Female/face_984_Latino_Hispanic_30-39', 'Roksana Pagacz', 'Female', 'Latino_Hispanic'),
('Female/face_985_East Asian_40-49', 'Przemyslaw Cholewka', 'Female', 'East Asian'),
('Male/face_986_Black_20-29', 'Eduard Vesely', 'Male', 'Black'),
('Male/face_987_Indian_20-29', 'Robert Marek', 'Male', 'Indian'),
('Male/face_988_East Asian_20-29', 'Mieszko Pera', 'Male', 'East Asian'),
('Male/face_989_Southeast Asian_3-9', 'Aleks Mieloch', 'Male', 'Southeast Asian'),
('Male/face_990_East Asian_50-59', 'Radoslav Pavlik', 'Male', 'East Asian'),
('Female/face_991_Latino_Hispanic_20-29', 'Rafal Ciarka', 'Female', 'Latino_Hispanic'),
('Male/face_992_White_40-49', 'Frantisek Fiser', 'Male', 'White'),
('Male/face_993_Black_40-49', 'Olaf Zdziech', 'Male', 'Black'),
('Female/face_994_Indian_20-29', 'Vera Kasparova', 'Female', 'Indian'),
('Male/face_995_Southeast Asian_10-19', 'Horvath Zoltan', 'Male', 'Southeast Asian'),
('Male/face_996_Southeast Asian_30-39', 'Klement Mach', 'Male', 'Southeast Asian'),
('Female/face_997_Indian_30-39', 'Anezka Dolezalova', 'Female', 'Indian'),
('Female/face_998_Middle Eastern_20-29', 'Vlasta Krejcova', 'Female', 'Middle Eastern'),
('Male/face_999_White_30-39', 'Svatoslav Valenta', 'Male', 'White'),
('Male/face_1000_Black_40-49', 'Jedrzej Jedrusiak', 'Male', 'Black')
